<?php

/**
 * BaseClassificationSlugLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $classification_id
 * @property char $lang
 * @property varchar $old_slug
 * @property Classification $Classification
 * 
 * @method integer               getClassificationId()  Returns the current record's "classification_id" value
 * @method char                  getLang()              Returns the current record's "lang" value
 * @method varchar               getOldSlug()           Returns the current record's "old_slug" value
 * @method Classification        getClassification()    Returns the current record's "Classification" value
 * @method ClassificationSlugLog setClassificationId()  Sets the current record's "classification_id" value
 * @method ClassificationSlugLog setLang()              Sets the current record's "lang" value
 * @method ClassificationSlugLog setOldSlug()           Sets the current record's "old_slug" value
 * @method ClassificationSlugLog setClassification()    Sets the current record's "Classification" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClassificationSlugLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('classification_slug_log');
        $this->hasColumn('classification_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('lang', 'char', 2, array(
             'type' => 'char',
             'length' => 2,
             ));
        $this->hasColumn('old_slug', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Classification', array(
             'local' => 'classification_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}