<?php

/**
 * BaseUserPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property UserProfile $UserProfile
 * 
 * @method UserProfile getUserProfile() Returns the current record's "UserProfile" value
 * @method UserPage    setUserProfile() Sets the current record's "UserProfile" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserPage extends Page
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserProfile', array(
             'local' => 'foreign_id',
             'foreign' => 'id'));
    }
}