<?php

/**
 * BaseCompanyImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $company_id
 * @property integer $image_id
 * @property Company $Company
 * @property Image $Image
 * 
 * @method integer      getCompanyId()  Returns the current record's "company_id" value
 * @method integer      getImageId()    Returns the current record's "image_id" value
 * @method Company      getCompany()    Returns the current record's "Company" value
 * @method Image        getImage()      Returns the current record's "Image" value
 * @method CompanyImage setCompanyId()  Sets the current record's "company_id" value
 * @method CompanyImage setImageId()    Sets the current record's "image_id" value
 * @method CompanyImage setCompany()    Sets the current record's "Company" value
 * @method CompanyImage setImage()      Sets the current record's "Image" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompanyImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company_image');
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('image_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Image', array(
             'local' => 'image_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}