<?php

/**
 * BaseCompany
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $external_id
 * @property string $title
 * @property string $description
 * @property string $content
 * @property string $email
 * @property string $phone
 * @property string $phone1
 * @property string $phone2
 * @property string $website_url
 * @property string $googleplus_url
 * @property string $foursquare_url
 * @property string $twitter_url
 * @property string $facebook_url
 * @property string $facebook_id
 * @property integer $city_id
 * @property integer $location_id
 * @property integer $image_id
 * @property integer $sector_id
 * @property integer $classification_id
 * @property integer $review_id
 * @property integer $company_type
 * @property integer $company_number
 * @property string $parent_external_id
 * @property enum $is_validated
 * @property enum $status
 * @property integer $number_of_reviews
 * @property float $average_rating
 * @property boolean $is_address_modified
 * @property string $registration_no
 * @property timestamp $updated_crm
 * @property timestamp $date_mod_crm
 * @property integer $created_by
 * @property decimal $score
 * @property integer $country_id
 * @property integer $last_modified_by
 * @property timestamp $date_last_modified_by
 * @property string $referer
 * @property string $old_slug
 * @property integer $cover_image_id
 * @property integer $logo_image_id
 * @property CoverImage $CoverImage
 * @property City $City
 * @property Sector $Sector
 * @property Classification $Classification
 * @property CompanyLocation $Location
 * @property UserProfile $CreatedByUser
 * @property Image $Image
 * @property Country $Country
 * @property Review $TopReview
 * @property UserProfile $UserProfile
 * @property Image $LogoImage
 * @property Doctrine_Collection $CompanyClassification
 * @property CompanyPage $CompanyPage
 * @property Doctrine_Collection $Menu
 * @property Doctrine_Collection $CompanyLocation
 * @property CompanyDetail $CompanyDetail
 * @property CompanyDetailSr $CompanyDetailSr
 * @property Doctrine_Collection $CompanyImage
 * @property Doctrine_Collection $ReportCompany
 * @property Doctrine_Collection $Review
 * @property Doctrine_Collection $CompanyOffer
 * @property CompanySearch $CompanySearch
 * @property Doctrine_Collection $AdServiceCompany
 * @property Doctrine_Collection $CompanyStats
 * @property Doctrine_Collection $CheckInStatus
 * @property Doctrine_Collection $CheckIn
 * @property Doctrine_Collection $getWeekend
 * @property Doctrine_Collection $getWeekendCompany
 * @property Doctrine_Collection $mailBgCampaign
 * @property Doctrine_Collection $CompanyStatus
 * @property Doctrine_Collection $FeatureCompany
 * @property Doctrine_Collection $CompanyExtra
 * 
 * @method string              getExternalId()            Returns the current record's "external_id" value
 * @method string              getTitle()                 Returns the current record's "title" value
 * @method string              getDescription()           Returns the current record's "description" value
 * @method string              getContent()               Returns the current record's "content" value
 * @method string              getEmail()                 Returns the current record's "email" value
 * @method string              getPhone()                 Returns the current record's "phone" value
 * @method string              getPhone1()                Returns the current record's "phone1" value
 * @method string              getPhone2()                Returns the current record's "phone2" value
 * @method string              getWebsiteUrl()            Returns the current record's "website_url" value
 * @method string              getGoogleplusUrl()         Returns the current record's "googleplus_url" value
 * @method string              getFoursquareUrl()         Returns the current record's "foursquare_url" value
 * @method string              getTwitterUrl()            Returns the current record's "twitter_url" value
 * @method string              getFacebookUrl()           Returns the current record's "facebook_url" value
 * @method string              getFacebookId()            Returns the current record's "facebook_id" value
 * @method integer             getCityId()                Returns the current record's "city_id" value
 * @method integer             getLocationId()            Returns the current record's "location_id" value
 * @method integer             getImageId()               Returns the current record's "image_id" value
 * @method integer             getSectorId()              Returns the current record's "sector_id" value
 * @method integer             getClassificationId()      Returns the current record's "classification_id" value
 * @method integer             getReviewId()              Returns the current record's "review_id" value
 * @method integer             getCompanyType()           Returns the current record's "company_type" value
 * @method integer             getCompanyNumber()         Returns the current record's "company_number" value
 * @method string              getParentExternalId()      Returns the current record's "parent_external_id" value
 * @method enum                getIsValidated()           Returns the current record's "is_validated" value
 * @method enum                getStatus()                Returns the current record's "status" value
 * @method integer             getNumberOfReviews()       Returns the current record's "number_of_reviews" value
 * @method float               getAverageRating()         Returns the current record's "average_rating" value
 * @method boolean             getIsAddressModified()     Returns the current record's "is_address_modified" value
 * @method string              getRegistrationNo()        Returns the current record's "registration_no" value
 * @method timestamp           getUpdatedCrm()            Returns the current record's "updated_crm" value
 * @method timestamp           getDateModCrm()            Returns the current record's "date_mod_crm" value
 * @method integer             getCreatedBy()             Returns the current record's "created_by" value
 * @method decimal             getScore()                 Returns the current record's "score" value
 * @method integer             getCountryId()             Returns the current record's "country_id" value
 * @method integer             getLastModifiedBy()        Returns the current record's "last_modified_by" value
 * @method timestamp           getDateLastModifiedBy()    Returns the current record's "date_last_modified_by" value
 * @method string              getReferer()               Returns the current record's "referer" value
 * @method string              getOldSlug()               Returns the current record's "old_slug" value
 * @method integer             getCoverImageId()          Returns the current record's "cover_image_id" value
 * @method integer             getLogoImageId()           Returns the current record's "logo_image_id" value
 * @method CoverImage          getCoverImage()            Returns the current record's "CoverImage" value
 * @method City                getCity()                  Returns the current record's "City" value
 * @method Sector              getSector()                Returns the current record's "Sector" value
 * @method Classification      getClassification()        Returns the current record's "Classification" value
 * @method CompanyLocation     getLocation()              Returns the current record's "Location" value
 * @method UserProfile         getCreatedByUser()         Returns the current record's "CreatedByUser" value
 * @method Image               getImage()                 Returns the current record's "Image" value
 * @method Country             getCountry()               Returns the current record's "Country" value
 * @method Review              getTopReview()             Returns the current record's "TopReview" value
 * @method UserProfile         getUserProfile()           Returns the current record's "UserProfile" value
 * @method Image               getLogoImage()             Returns the current record's "LogoImage" value
 * @method Doctrine_Collection getCompanyClassification() Returns the current record's "CompanyClassification" collection
 * @method CompanyPage         getCompanyPage()           Returns the current record's "CompanyPage" value
 * @method Doctrine_Collection getMenu()                  Returns the current record's "Menu" collection
 * @method Doctrine_Collection getCompanyLocation()       Returns the current record's "CompanyLocation" collection
 * @method CompanyDetail       getCompanyDetail()         Returns the current record's "CompanyDetail" value
 * @method CompanyDetailSr     getCompanyDetailSr()       Returns the current record's "CompanyDetailSr" value
 * @method Doctrine_Collection getCompanyImage()          Returns the current record's "CompanyImage" collection
 * @method Doctrine_Collection getReportCompany()         Returns the current record's "ReportCompany" collection
 * @method Doctrine_Collection getReview()                Returns the current record's "Review" collection
 * @method Doctrine_Collection getCompanyOffer()          Returns the current record's "CompanyOffer" collection
 * @method CompanySearch       getCompanySearch()         Returns the current record's "CompanySearch" value
 * @method Doctrine_Collection getAdServiceCompany()      Returns the current record's "AdServiceCompany" collection
 * @method Doctrine_Collection getCompanyStats()          Returns the current record's "CompanyStats" collection
 * @method Doctrine_Collection getCheckInStatus()         Returns the current record's "CheckInStatus" collection
 * @method Doctrine_Collection getCheckIn()               Returns the current record's "CheckIn" collection
 * @method Doctrine_Collection getGetWeekend()            Returns the current record's "getWeekend" collection
 * @method Doctrine_Collection getGetWeekendCompany()     Returns the current record's "getWeekendCompany" collection
 * @method Doctrine_Collection getMailBgCampaign()        Returns the current record's "mailBgCampaign" collection
 * @method Doctrine_Collection getCompanyStatus()         Returns the current record's "CompanyStatus" collection
 * @method Doctrine_Collection getFeatureCompany()        Returns the current record's "FeatureCompany" collection
 * @method Doctrine_Collection getCompanyExtra()          Returns the current record's "CompanyExtra" collection
 * @method Company             setExternalId()            Sets the current record's "external_id" value
 * @method Company             setTitle()                 Sets the current record's "title" value
 * @method Company             setDescription()           Sets the current record's "description" value
 * @method Company             setContent()               Sets the current record's "content" value
 * @method Company             setEmail()                 Sets the current record's "email" value
 * @method Company             setPhone()                 Sets the current record's "phone" value
 * @method Company             setPhone1()                Sets the current record's "phone1" value
 * @method Company             setPhone2()                Sets the current record's "phone2" value
 * @method Company             setWebsiteUrl()            Sets the current record's "website_url" value
 * @method Company             setGoogleplusUrl()         Sets the current record's "googleplus_url" value
 * @method Company             setFoursquareUrl()         Sets the current record's "foursquare_url" value
 * @method Company             setTwitterUrl()            Sets the current record's "twitter_url" value
 * @method Company             setFacebookUrl()           Sets the current record's "facebook_url" value
 * @method Company             setFacebookId()            Sets the current record's "facebook_id" value
 * @method Company             setCityId()                Sets the current record's "city_id" value
 * @method Company             setLocationId()            Sets the current record's "location_id" value
 * @method Company             setImageId()               Sets the current record's "image_id" value
 * @method Company             setSectorId()              Sets the current record's "sector_id" value
 * @method Company             setClassificationId()      Sets the current record's "classification_id" value
 * @method Company             setReviewId()              Sets the current record's "review_id" value
 * @method Company             setCompanyType()           Sets the current record's "company_type" value
 * @method Company             setCompanyNumber()         Sets the current record's "company_number" value
 * @method Company             setParentExternalId()      Sets the current record's "parent_external_id" value
 * @method Company             setIsValidated()           Sets the current record's "is_validated" value
 * @method Company             setStatus()                Sets the current record's "status" value
 * @method Company             setNumberOfReviews()       Sets the current record's "number_of_reviews" value
 * @method Company             setAverageRating()         Sets the current record's "average_rating" value
 * @method Company             setIsAddressModified()     Sets the current record's "is_address_modified" value
 * @method Company             setRegistrationNo()        Sets the current record's "registration_no" value
 * @method Company             setUpdatedCrm()            Sets the current record's "updated_crm" value
 * @method Company             setDateModCrm()            Sets the current record's "date_mod_crm" value
 * @method Company             setCreatedBy()             Sets the current record's "created_by" value
 * @method Company             setScore()                 Sets the current record's "score" value
 * @method Company             setCountryId()             Sets the current record's "country_id" value
 * @method Company             setLastModifiedBy()        Sets the current record's "last_modified_by" value
 * @method Company             setDateLastModifiedBy()    Sets the current record's "date_last_modified_by" value
 * @method Company             setReferer()               Sets the current record's "referer" value
 * @method Company             setOldSlug()               Sets the current record's "old_slug" value
 * @method Company             setCoverImageId()          Sets the current record's "cover_image_id" value
 * @method Company             setLogoImageId()           Sets the current record's "logo_image_id" value
 * @method Company             setCoverImage()            Sets the current record's "CoverImage" value
 * @method Company             setCity()                  Sets the current record's "City" value
 * @method Company             setSector()                Sets the current record's "Sector" value
 * @method Company             setClassification()        Sets the current record's "Classification" value
 * @method Company             setLocation()              Sets the current record's "Location" value
 * @method Company             setCreatedByUser()         Sets the current record's "CreatedByUser" value
 * @method Company             setImage()                 Sets the current record's "Image" value
 * @method Company             setCountry()               Sets the current record's "Country" value
 * @method Company             setTopReview()             Sets the current record's "TopReview" value
 * @method Company             setUserProfile()           Sets the current record's "UserProfile" value
 * @method Company             setLogoImage()             Sets the current record's "LogoImage" value
 * @method Company             setCompanyClassification() Sets the current record's "CompanyClassification" collection
 * @method Company             setCompanyPage()           Sets the current record's "CompanyPage" value
 * @method Company             setMenu()                  Sets the current record's "Menu" collection
 * @method Company             setCompanyLocation()       Sets the current record's "CompanyLocation" collection
 * @method Company             setCompanyDetail()         Sets the current record's "CompanyDetail" value
 * @method Company             setCompanyDetailSr()       Sets the current record's "CompanyDetailSr" value
 * @method Company             setCompanyImage()          Sets the current record's "CompanyImage" collection
 * @method Company             setReportCompany()         Sets the current record's "ReportCompany" collection
 * @method Company             setReview()                Sets the current record's "Review" collection
 * @method Company             setCompanyOffer()          Sets the current record's "CompanyOffer" collection
 * @method Company             setCompanySearch()         Sets the current record's "CompanySearch" value
 * @method Company             setAdServiceCompany()      Sets the current record's "AdServiceCompany" collection
 * @method Company             setCompanyStats()          Sets the current record's "CompanyStats" collection
 * @method Company             setCheckInStatus()         Sets the current record's "CheckInStatus" collection
 * @method Company             setCheckIn()               Sets the current record's "CheckIn" collection
 * @method Company             setGetWeekend()            Sets the current record's "getWeekend" collection
 * @method Company             setGetWeekendCompany()     Sets the current record's "getWeekendCompany" collection
 * @method Company             setMailBgCampaign()        Sets the current record's "mailBgCampaign" collection
 * @method Company             setCompanyStatus()         Sets the current record's "CompanyStatus" collection
 * @method Company             setFeatureCompany()        Sets the current record's "FeatureCompany" collection
 * @method Company             setCompanyExtra()          Sets the current record's "CompanyExtra" collection
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompany extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company');
        $this->hasColumn('external_id', 'string', 36, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 36,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('email', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('website_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('googleplus_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('foursquare_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('twitter_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('facebook_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('facebook_id', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('city_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('location_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('image_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sector_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('classification_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('review_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('company_type', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('company_number', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('parent_external_id', 'string', 36, array(
             'type' => 'string',
             'length' => 36,
             ));
        $this->hasColumn('is_validated', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'not_validated',
              1 => 'validation_started',
              2 => 'awaiting_approval',
              3 => 'validated',
             ),
             'default' => 'not_validated',
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'approved',
              1 => 'rejected',
              2 => 'pending',
              3 => 'invisible',
             ),
             'default' => 'pending',
             ));
        $this->hasColumn('number_of_reviews', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('average_rating', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             ));
        $this->hasColumn('is_address_modified', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('registration_no', 'string', 14, array(
             'type' => 'string',
             'length' => 14,
             ));
        $this->hasColumn('updated_crm', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('date_mod_crm', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('created_by', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('score', 'decimal', 5, array(
             'type' => 'decimal',
             'scale' => 2,
             'default' => 1,
             'length' => 5,
             ));
        $this->hasColumn('country_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('last_modified_by', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('date_last_modified_by', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('referer', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('old_slug', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cover_image_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('logo_image_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('old_id', array(
             'fields' => 
             array(
              0 => 'external_id',
             ),
             ));
        $this->index('rating', array(
             'fields' => 
             array(
              0 => 'average_rating',
              1 => 'number_of_reviews',
             ),
             ));
        $this->index('reviews', array(
             'fields' => 
             array(
              0 => 'number_of_reviews',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CoverImage', array(
             'local' => 'cover_image_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('City', array(
             'local' => 'city_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Sector', array(
             'local' => 'sector_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Classification', array(
             'local' => 'classification_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('CompanyLocation as Location', array(
             'local' => 'location_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('UserProfile as CreatedByUser', array(
             'local' => 'created_by',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Image', array(
             'local' => 'image_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Country', array(
             'local' => 'country_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Review as TopReview', array(
             'local' => 'review_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('UserProfile', array(
             'local' => 'last_modified_by',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Image as LogoImage', array(
             'local' => 'logo_image_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('CompanyClassification', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasOne('CompanyPage', array(
             'local' => 'id',
             'foreign' => 'foreign_id'));

        $this->hasMany('Menu', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasMany('CompanyLocation', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasOne('CompanyDetail', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasOne('CompanyDetailSr', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasMany('CompanyImage', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasMany('ReportCompany', array(
             'local' => 'id',
             'foreign' => 'object_id'));

        $this->hasMany('Review', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasMany('CompanyOffer', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasOne('CompanySearch', array(
             'local' => 'id',
             'foreign' => 'object_id'));

        $this->hasMany('AdServiceCompany', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasMany('CompanyStats', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasMany('CheckInStatus', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasMany('CheckIn', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasMany('getWeekend', array(
             'refClass' => 'getWeekendCompany',
             'local' => 'company_id',
             'foreign' => 'parent_id'));

        $this->hasMany('getWeekendCompany', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasMany('mailBgCampaign', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasMany('CompanyStatus', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $this->hasMany('FeatureCompany', array(
             'refClass' => 'CompanyFeatureCompany',
             'local' => 'company_id',
             'foreign' => 'feature_id'));

        $this->hasMany('CompanyExtra', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'description',
              2 => 'content',
             ),
             ));
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => false,
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
        $this->actAs($sluggable0);
    }
}