<?php

/**
 * BaseinvitedUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $email
 * @property string $facebook_uid
 * @property string $hash
 * @property enum $invited_from
 * @property integer $points_to_invited
 * @property integer $points_to_user
 * @property integer $user_id
 * @property UserProfile $UserProfile
 * 
 * @method string      getEmail()             Returns the current record's "email" value
 * @method string      getFacebookUid()       Returns the current record's "facebook_uid" value
 * @method string      getHash()              Returns the current record's "hash" value
 * @method enum        getInvitedFrom()       Returns the current record's "invited_from" value
 * @method integer     getPointsToInvited()   Returns the current record's "points_to_invited" value
 * @method integer     getPointsToUser()      Returns the current record's "points_to_user" value
 * @method integer     getUserId()            Returns the current record's "user_id" value
 * @method UserProfile getUserProfile()       Returns the current record's "UserProfile" value
 * @method invitedUser setEmail()             Sets the current record's "email" value
 * @method invitedUser setFacebookUid()       Sets the current record's "facebook_uid" value
 * @method invitedUser setHash()              Sets the current record's "hash" value
 * @method invitedUser setInvitedFrom()       Sets the current record's "invited_from" value
 * @method invitedUser setPointsToInvited()   Sets the current record's "points_to_invited" value
 * @method invitedUser setPointsToUser()      Sets the current record's "points_to_user" value
 * @method invitedUser setUserId()            Sets the current record's "user_id" value
 * @method invitedUser setUserProfile()       Sets the current record's "UserProfile" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseinvitedUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('invited_user');
        $this->hasColumn('email', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('facebook_uid', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('hash', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('invited_from', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'email',
              1 => 'gmail_yahoo',
              2 => 'facebook',
             ),
             ));
        $this->hasColumn('points_to_invited', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('points_to_user', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('user_data', array(
             'fields' => 
             array(
              0 => 'email',
              1 => 'facebook_uid',
             ),
             ));
        $this->option('symfony', array(
             'form' => true,
             'filter' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserProfile', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}