<?php

/**
 * BaseUserSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $show_profile
 * @property boolean $search_name
 * @property boolean $search_nickname
 * @property boolean $search_email
 * @property boolean $show_age
 * @property boolean $show_gender
 * @property boolean $show_online
 * @property boolean $public_comments
 * @property boolean $auto_comments
 * @property boolean $allow_contact
 * @property boolean $allow_localization
 * @property boolean $allow_newsletter
 * @property boolean $allow_b_cmc
 * @property boolean $allow_promo
 * @property boolean $underage
 * @property UserProfile $UserProfile
 * 
 * @method boolean     getShowProfile()        Returns the current record's "show_profile" value
 * @method boolean     getSearchName()         Returns the current record's "search_name" value
 * @method boolean     getSearchNickname()     Returns the current record's "search_nickname" value
 * @method boolean     getSearchEmail()        Returns the current record's "search_email" value
 * @method boolean     getShowAge()            Returns the current record's "show_age" value
 * @method boolean     getShowGender()         Returns the current record's "show_gender" value
 * @method boolean     getShowOnline()         Returns the current record's "show_online" value
 * @method boolean     getPublicComments()     Returns the current record's "public_comments" value
 * @method boolean     getAutoComments()       Returns the current record's "auto_comments" value
 * @method boolean     getAllowContact()       Returns the current record's "allow_contact" value
 * @method boolean     getAllowLocalization()  Returns the current record's "allow_localization" value
 * @method boolean     getAllowNewsletter()    Returns the current record's "allow_newsletter" value
 * @method boolean     getAllowBCmc()          Returns the current record's "allow_b_cmc" value
 * @method boolean     getAllowPromo()         Returns the current record's "allow_promo" value
 * @method boolean     getUnderage()           Returns the current record's "underage" value
 * @method UserProfile getUserProfile()        Returns the current record's "UserProfile" value
 * @method UserSetting setShowProfile()        Sets the current record's "show_profile" value
 * @method UserSetting setSearchName()         Sets the current record's "search_name" value
 * @method UserSetting setSearchNickname()     Sets the current record's "search_nickname" value
 * @method UserSetting setSearchEmail()        Sets the current record's "search_email" value
 * @method UserSetting setShowAge()            Sets the current record's "show_age" value
 * @method UserSetting setShowGender()         Sets the current record's "show_gender" value
 * @method UserSetting setShowOnline()         Sets the current record's "show_online" value
 * @method UserSetting setPublicComments()     Sets the current record's "public_comments" value
 * @method UserSetting setAutoComments()       Sets the current record's "auto_comments" value
 * @method UserSetting setAllowContact()       Sets the current record's "allow_contact" value
 * @method UserSetting setAllowLocalization()  Sets the current record's "allow_localization" value
 * @method UserSetting setAllowNewsletter()    Sets the current record's "allow_newsletter" value
 * @method UserSetting setAllowBCmc()          Sets the current record's "allow_b_cmc" value
 * @method UserSetting setAllowPromo()         Sets the current record's "allow_promo" value
 * @method UserSetting setUnderage()           Sets the current record's "underage" value
 * @method UserSetting setUserProfile()        Sets the current record's "UserProfile" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserSetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_setting');
        $this->hasColumn('show_profile', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('search_name', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('search_nickname', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('search_email', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('show_age', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('show_gender', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('show_online', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('public_comments', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('auto_comments', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('allow_contact', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('allow_localization', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('allow_newsletter', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('allow_b_cmc', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('allow_promo', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('underage', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserProfile', array(
             'local' => 'id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}