<?php

/**
 * BaseSearchHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $word
 * @property string $culture
 * @property integer $count
 * @property integer $results_count
 * 
 * @method string        getWord()          Returns the current record's "word" value
 * @method string        getCulture()       Returns the current record's "culture" value
 * @method integer       getCount()         Returns the current record's "count" value
 * @method integer       getResultsCount()  Returns the current record's "results_count" value
 * @method SearchHistory setWord()          Sets the current record's "word" value
 * @method SearchHistory setCulture()       Sets the current record's "culture" value
 * @method SearchHistory setCount()         Sets the current record's "count" value
 * @method SearchHistory setResultsCount()  Sets the current record's "results_count" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSearchHistory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('search_history');
        $this->hasColumn('word', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('culture', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'en',
             'length' => 50,
             ));
        $this->hasColumn('count', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('results_count', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));


        $this->index('word', array(
             'fields' => 
             array(
              0 => 'word',
             ),
             ));
        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}