<?php

/**
 * BaseBoxToZone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $box_id
 * @property string $key
 * @property integer $col_no
 * @property integer $weight
 * @property array $settings
 * @property Box $Box
 * 
 * @method integer   getBoxId()    Returns the current record's "box_id" value
 * @method string    getKey()      Returns the current record's "key" value
 * @method integer   getColNo()    Returns the current record's "col_no" value
 * @method integer   getWeight()   Returns the current record's "weight" value
 * @method array     getSettings() Returns the current record's "settings" value
 * @method Box       getBox()      Returns the current record's "Box" value
 * @method BoxToZone setBoxId()    Sets the current record's "box_id" value
 * @method BoxToZone setKey()      Sets the current record's "key" value
 * @method BoxToZone setColNo()    Sets the current record's "col_no" value
 * @method BoxToZone setWeight()   Sets the current record's "weight" value
 * @method BoxToZone setSettings() Sets the current record's "settings" value
 * @method BoxToZone setBox()      Sets the current record's "Box" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBoxToZone extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('box_to_zone');
        $this->hasColumn('box_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('keyName as key', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('col_no', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('weight', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('settings', 'array', null, array(
             'type' => 'array',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Box', array(
             'local' => 'box_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}