<?php

/**
 * BaseSectorSlugLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sector_id
 * @property char $lang
 * @property varchar $old_slug
 * @property Sector $Sector
 * 
 * @method integer       getSectorId()  Returns the current record's "sector_id" value
 * @method char          getLang()      Returns the current record's "lang" value
 * @method varchar       getOldSlug()   Returns the current record's "old_slug" value
 * @method Sector        getSector()    Returns the current record's "Sector" value
 * @method SectorSlugLog setSectorId()  Sets the current record's "sector_id" value
 * @method SectorSlugLog setLang()      Sets the current record's "lang" value
 * @method SectorSlugLog setOldSlug()   Sets the current record's "old_slug" value
 * @method SectorSlugLog setSector()    Sets the current record's "Sector" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSectorSlugLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sector_slug_log');
        $this->hasColumn('sector_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('lang', 'char', 2, array(
             'type' => 'char',
             'length' => 2,
             ));
        $this->hasColumn('old_slug', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Sector', array(
             'local' => 'sector_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}