<?php

/**
 * BaseCompanyClassification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $classification_id
 * @property integer $company_id
 * @property Classification $Classification
 * @property Company $Company
 * 
 * @method integer               getClassificationId()  Returns the current record's "classification_id" value
 * @method integer               getCompanyId()         Returns the current record's "company_id" value
 * @method Classification        getClassification()    Returns the current record's "Classification" value
 * @method Company               getCompany()           Returns the current record's "Company" value
 * @method CompanyClassification setClassificationId()  Sets the current record's "classification_id" value
 * @method CompanyClassification setCompanyId()         Sets the current record's "company_id" value
 * @method CompanyClassification setClassification()    Sets the current record's "Classification" value
 * @method CompanyClassification setCompany()           Sets the current record's "Company" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompanyClassification extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company_classification');
        $this->hasColumn('classification_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Classification', array(
             'local' => 'classification_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}