<?php

/**
 * BaseCompanyFeatureCompany
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $feature_id
 * @property integer $company_id
 * 
 * @method integer               getFeatureId()  Returns the current record's "feature_id" value
 * @method integer               getCompanyId()  Returns the current record's "company_id" value
 * @method CompanyFeatureCompany setFeatureId()  Sets the current record's "feature_id" value
 * @method CompanyFeatureCompany setCompanyId()  Sets the current record's "company_id" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompanyFeatureCompany extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company_feature_company');
        $this->hasColumn('feature_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}