<?php

/**
 * BaseSearch
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $body
 * @property string $keywords
 * @property integer $object_id
 * @property string $culture
 * @property string $model_name
 * 
 * @method string  getTitle()      Returns the current record's "title" value
 * @method string  getBody()       Returns the current record's "body" value
 * @method string  getKeywords()   Returns the current record's "keywords" value
 * @method integer getObjectId()   Returns the current record's "object_id" value
 * @method string  getCulture()    Returns the current record's "culture" value
 * @method string  getModelName()  Returns the current record's "model_name" value
 * @method Search  setTitle()      Sets the current record's "title" value
 * @method Search  setBody()       Sets the current record's "body" value
 * @method Search  setKeywords()   Sets the current record's "keywords" value
 * @method Search  setObjectId()   Sets the current record's "object_id" value
 * @method Search  setCulture()    Sets the current record's "culture" value
 * @method Search  setModelName()  Sets the current record's "model_name" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSearch extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('search');
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('keywords', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('object_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('culture', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('model_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('search', array(
             'fields' => 
             array(
              'title' => 
              array(
              ),
              'body' => 
              array(
              ),
              'keywords' => 
              array(
              ),
             ),
             'type' => 'fulltext',
             ));
        $this->index('object', array(
             'fields' => 
             array(
              0 => 'object_id',
              1 => 'model_name',
              2 => 'culture',
             ),
             ));
        $this->option('type', 'MyISAM');
        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));

        $this->setSubClasses(array(
             'CompanySearch' => 
             array(
              'model_name' => 'Company',
             ),
             'EventSearch' => 
             array(
              'model_name' => 'Event',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}