<?php

/**
 * BaseUrlMap
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $old_url
 * @property string $new_url
 * 
 * @method string getOldUrl()  Returns the current record's "old_url" value
 * @method string getNewUrl()  Returns the current record's "new_url" value
 * @method UrlMap setOldUrl()  Sets the current record's "old_url" value
 * @method UrlMap setNewUrl()  Sets the current record's "new_url" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUrlMap extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('url_map');
        $this->hasColumn('old_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('new_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}