<?php

/**
 * BaseSerbianCities
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $city_id
 * @property string $city_change
 * @property City $City
 * 
 * @method integer       getCityId()      Returns the current record's "city_id" value
 * @method string        getCityChange()  Returns the current record's "city_change" value
 * @method City          getCity()        Returns the current record's "City" value
 * @method SerbianCities setCityId()      Sets the current record's "city_id" value
 * @method SerbianCities setCityChange()  Sets the current record's "city_change" value
 * @method SerbianCities setCity()        Sets the current record's "City" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSerbianCities extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('serbian_cities');
        $this->hasColumn('city_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('city_change', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('City', array(
             'local' => 'city_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}