<?php

/**
 * BaseReportImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Image $Image
 * 
 * @method Image       getImage() Returns the current record's "Image" value
 * @method ReportImage setImage() Sets the current record's "Image" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReportImage extends Report
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Image', array(
             'local' => 'object_id',
             'foreign' => 'id'));
    }
}