<?php

/**
 * BaseAdService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $name
 * @property string $short_description
 * @property boolean $is_active
 * @property boolean $status
 * @property Doctrine_Collection $AdServiceCompany
 * 
 * @method string              getCode()              Returns the current record's "code" value
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getShortDescription()  Returns the current record's "short_description" value
 * @method boolean             getIsActive()          Returns the current record's "is_active" value
 * @method boolean             getStatus()            Returns the current record's "status" value
 * @method Doctrine_Collection getAdServiceCompany()  Returns the current record's "AdServiceCompany" collection
 * @method AdService           setCode()              Sets the current record's "code" value
 * @method AdService           setName()              Sets the current record's "name" value
 * @method AdService           setShortDescription()  Sets the current record's "short_description" value
 * @method AdService           setIsActive()          Sets the current record's "is_active" value
 * @method AdService           setStatus()            Sets the current record's "status" value
 * @method AdService           setAdServiceCompany()  Sets the current record's "AdServiceCompany" collection
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdService extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_service');
        $this->hasColumn('code', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('short_description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AdServiceCompany', array(
             'local' => 'id',
             'foreign' => 'ad_service_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'short_description',
              2 => 'is_active',
             ),
             ));
        $this->actAs($i18n0);
    }
}