<?php

/**
 * BaseArticleImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property integer $user_id
 * @property string $filename
 * @property string $descrption
 * @property string $source
 * @property string $code
 * @property integer $rank
 * @property Article $Article
 * @property UserProfile $UserProfile
 * 
 * @method integer      getArticleId()   Returns the current record's "article_id" value
 * @method integer      getUserId()      Returns the current record's "user_id" value
 * @method string       getFilename()    Returns the current record's "filename" value
 * @method string       getDescrption()  Returns the current record's "descrption" value
 * @method string       getSource()      Returns the current record's "source" value
 * @method string       getCode()        Returns the current record's "code" value
 * @method integer      getRank()        Returns the current record's "rank" value
 * @method Article      getArticle()     Returns the current record's "Article" value
 * @method UserProfile  getUserProfile() Returns the current record's "UserProfile" value
 * @method ArticleImage setArticleId()   Sets the current record's "article_id" value
 * @method ArticleImage setUserId()      Sets the current record's "user_id" value
 * @method ArticleImage setFilename()    Sets the current record's "filename" value
 * @method ArticleImage setDescrption()  Sets the current record's "descrption" value
 * @method ArticleImage setSource()      Sets the current record's "source" value
 * @method ArticleImage setCode()        Sets the current record's "code" value
 * @method ArticleImage setRank()        Sets the current record's "rank" value
 * @method ArticleImage setArticle()     Sets the current record's "Article" value
 * @method ArticleImage setUserProfile() Sets the current record's "UserProfile" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticleImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article_image');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('descrption', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('source', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('rank', 'integer', 4, array(
             'type' => 'integer',
             'default' => 1,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('UserProfile', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}