<?php

/**
 * BaseCategoryArticleClassification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $classification_id
 * 
 * @method integer                       getCategoryId()        Returns the current record's "category_id" value
 * @method integer                       getClassificationId()  Returns the current record's "classification_id" value
 * @method CategoryArticleClassification setCategoryId()        Sets the current record's "category_id" value
 * @method CategoryArticleClassification setClassificationId()  Sets the current record's "classification_id" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryArticleClassification extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_article_classification');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('classification_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}