<?php

/**
 * BaseSliderCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $slider_id
 * @property integer $city_id
 * @property Slider $Slider
 * @property City $City
 * 
 * @method integer    getSliderId()  Returns the current record's "slider_id" value
 * @method integer    getCityId()    Returns the current record's "city_id" value
 * @method Slider     getSlider()    Returns the current record's "Slider" value
 * @method City       getCity()      Returns the current record's "City" value
 * @method SliderCity setSliderId()  Sets the current record's "slider_id" value
 * @method SliderCity setCityId()    Sets the current record's "city_id" value
 * @method SliderCity setSlider()    Sets the current record's "Slider" value
 * @method SliderCity setCity()      Sets the current record's "City" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSliderCity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('slider_city');
        $this->hasColumn('slider_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('city_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Slider', array(
             'local' => 'slider_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('City', array(
             'local' => 'city_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}