<?php

/**
 * BasegetWeekend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $title_en
 * @property string $body
 * @property string $body_en
 * @property string $embed
 * @property date $aired_on
 * @property integer $country_id
 * @property boolean $is_active
 * @property Doctrine_Collection $Companies
 * @property Doctrine_Collection $Events
 * @property Doctrine_Collection $getWeekendCompany
 * @property Doctrine_Collection $getWeekendEvent
 * 
 * @method string              getTitle()             Returns the current record's "title" value
 * @method string              getTitleEn()           Returns the current record's "title_en" value
 * @method string              getBody()              Returns the current record's "body" value
 * @method string              getBodyEn()            Returns the current record's "body_en" value
 * @method string              getEmbed()             Returns the current record's "embed" value
 * @method date                getAiredOn()           Returns the current record's "aired_on" value
 * @method integer             getCountryId()         Returns the current record's "country_id" value
 * @method boolean             getIsActive()          Returns the current record's "is_active" value
 * @method Doctrine_Collection getCompanies()         Returns the current record's "Companies" collection
 * @method Doctrine_Collection getEvents()            Returns the current record's "Events" collection
 * @method Doctrine_Collection getGetWeekendCompany() Returns the current record's "getWeekendCompany" collection
 * @method Doctrine_Collection getGetWeekendEvent()   Returns the current record's "getWeekendEvent" collection
 * @method getWeekend          setTitle()             Sets the current record's "title" value
 * @method getWeekend          setTitleEn()           Sets the current record's "title_en" value
 * @method getWeekend          setBody()              Sets the current record's "body" value
 * @method getWeekend          setBodyEn()            Sets the current record's "body_en" value
 * @method getWeekend          setEmbed()             Sets the current record's "embed" value
 * @method getWeekend          setAiredOn()           Sets the current record's "aired_on" value
 * @method getWeekend          setCountryId()         Sets the current record's "country_id" value
 * @method getWeekend          setIsActive()          Sets the current record's "is_active" value
 * @method getWeekend          setCompanies()         Sets the current record's "Companies" collection
 * @method getWeekend          setEvents()            Sets the current record's "Events" collection
 * @method getWeekend          setGetWeekendCompany() Sets the current record's "getWeekendCompany" collection
 * @method getWeekend          setGetWeekendEvent()   Sets the current record's "getWeekendEvent" collection
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasegetWeekend extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('get_weekend');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title_en', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('body_en', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('embed', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('aired_on', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('country_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Company as Companies', array(
             'refClass' => 'getWeekendCompany',
             'local' => 'parent_id',
             'foreign' => 'company_id'));

        $this->hasMany('Event as Events', array(
             'refClass' => 'getWeekendEvent',
             'local' => 'parent_id',
             'foreign' => 'event_id'));

        $this->hasMany('getWeekendCompany', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $this->hasMany('getWeekendEvent', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $doctrineclusterstorage0 = new DoctrineClusterStorage(array(
             'filename' => 
             array(
              'is_image' => true,
              'sizes' => 
              array(
              0 => '295x170',
              1 => '63x63',
              ),
              'prefix' => 'getweekend',
              'sizefield_name' => false,
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($doctrineclusterstorage0);
    }
}