<?php

/**
 * BaseActivityPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Page $Page
 * @property Activity $Activity
 * 
 * @method Page         getPage()     Returns the current record's "Page" value
 * @method Activity     getActivity() Returns the current record's "Activity" value
 * @method ActivityPage setPage()     Sets the current record's "Page" value
 * @method ActivityPage setActivity() Sets the current record's "Activity" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivityPage extends Activity
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Page', array(
             'local' => 'action_id',
             'foreign' => 'id'));

        $this->hasOne('Activity', array(
             'local' => 'activity_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}