<?php

/**
 * BaseCategorySector
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $sector_id
 * @property Category $Category
 * @property Sector $Sector
 * 
 * @method integer        getCategoryId()  Returns the current record's "category_id" value
 * @method integer        getSectorId()    Returns the current record's "sector_id" value
 * @method Category       getCategory()    Returns the current record's "Category" value
 * @method Sector         getSector()      Returns the current record's "Sector" value
 * @method CategorySector setCategoryId()  Sets the current record's "category_id" value
 * @method CategorySector setSectorId()    Sets the current record's "sector_id" value
 * @method CategorySector setCategory()    Sets the current record's "Category" value
 * @method CategorySector setSector()      Sets the current record's "Sector" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategorySector extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_sector');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sector_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Sector', array(
             'local' => 'sector_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}