<?php

/**
 * BasePilotVote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $video_id
 * @property sfGuardUser $User
 * @property PilotVideo $PilotVideo
 * 
 * @method integer     getUserId()     Returns the current record's "user_id" value
 * @method integer     getVideoId()    Returns the current record's "video_id" value
 * @method sfGuardUser getUser()       Returns the current record's "User" value
 * @method PilotVideo  getPilotVideo() Returns the current record's "PilotVideo" value
 * @method PilotVote   setUserId()     Sets the current record's "user_id" value
 * @method PilotVote   setVideoId()    Sets the current record's "video_id" value
 * @method PilotVote   setUser()       Sets the current record's "User" value
 * @method PilotVote   setPilotVideo() Sets the current record's "PilotVideo" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePilotVote extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pilot_vote');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('video_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('PilotVideo', array(
             'local' => 'video_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}