<?php

/**
 * BaseCategoryClassification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $classification_id
 * @property Category $Category
 * @property Classification $Classification
 * 
 * @method integer                getCategoryId()        Returns the current record's "category_id" value
 * @method integer                getClassificationId()  Returns the current record's "classification_id" value
 * @method Category               getCategory()          Returns the current record's "Category" value
 * @method Classification         getClassification()    Returns the current record's "Classification" value
 * @method CategoryClassification setCategoryId()        Sets the current record's "category_id" value
 * @method CategoryClassification setClassificationId()  Sets the current record's "classification_id" value
 * @method CategoryClassification setCategory()          Sets the current record's "Category" value
 * @method CategoryClassification setClassification()    Sets the current record's "Classification" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryClassification extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_classification');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('classification_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Classification', array(
             'local' => 'classification_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}