<?php

/**
 * BaseActivityCompanyOffer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property CompanyOffer $CompanyOffer
 * 
 * @method CompanyOffer         getCompanyOffer() Returns the current record's "CompanyOffer" value
 * @method ActivityCompanyOffer setCompanyOffer() Sets the current record's "CompanyOffer" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivityCompanyOffer extends Activity
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CompanyOffer', array(
             'local' => 'action_id',
             'foreign' => 'id'));
    }
}