<?php

/**
 * BaseCategoryArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property boolean $is_active
 * @property varchar $slug
 * @property enum $status
 * @property Doctrine_Collection $Country
 * @property Doctrine_Collection $Classification
 * @property Doctrine_Collection $ArticleCategory
 * 
 * @method string              getTitle()           Returns the current record's "title" value
 * @method boolean             getIsActive()        Returns the current record's "is_active" value
 * @method varchar             getSlug()            Returns the current record's "slug" value
 * @method enum                getStatus()          Returns the current record's "status" value
 * @method Doctrine_Collection getCountry()         Returns the current record's "Country" collection
 * @method Doctrine_Collection getClassification()  Returns the current record's "Classification" collection
 * @method Doctrine_Collection getArticleCategory() Returns the current record's "ArticleCategory" collection
 * @method CategoryArticle     setTitle()           Sets the current record's "title" value
 * @method CategoryArticle     setIsActive()        Sets the current record's "is_active" value
 * @method CategoryArticle     setSlug()            Sets the current record's "slug" value
 * @method CategoryArticle     setStatus()          Sets the current record's "status" value
 * @method CategoryArticle     setCountry()         Sets the current record's "Country" collection
 * @method CategoryArticle     setClassification()  Sets the current record's "Classification" collection
 * @method CategoryArticle     setArticleCategory() Sets the current record's "ArticleCategory" collection
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_article');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('slug', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'approved',
              1 => 'pending',
              2 => 'rejected',
             ),
             'default' => 'approved',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Country', array(
             'refClass' => 'CategoryArticleCountry',
             'local' => 'category_id',
             'foreign' => 'country_id',
             'onDelete' => 'CASCADE,'));

        $this->hasMany('Classification', array(
             'refClass' => 'CategoryArticleClassification',
             'local' => 'category_id',
             'foreign' => 'classification_id',
             'onDelete' => 'CASCADE,'));

        $this->hasMany('ArticleCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'slug',
              2 => 'is_active',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             'uniqueBy' => 
             array(
              0 => 'lang',
             ),
             'canUpdate' => false,
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}