<?php

/**
 * BaseBox
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $module
 * @property string $component
 * @property array $settings
 * @property Doctrine_Collection $BoxToZone
 * 
 * @method string              getModule()    Returns the current record's "module" value
 * @method string              getComponent() Returns the current record's "component" value
 * @method array               getSettings()  Returns the current record's "settings" value
 * @method Doctrine_Collection getBoxToZone() Returns the current record's "BoxToZone" collection
 * @method Box                 setModule()    Sets the current record's "module" value
 * @method Box                 setComponent() Sets the current record's "component" value
 * @method Box                 setSettings()  Sets the current record's "settings" value
 * @method Box                 setBoxToZone() Sets the current record's "BoxToZone" collection
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBox extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('box');
        $this->hasColumn('module', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('component', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('settings', 'array', null, array(
             'type' => 'array',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BoxToZone', array(
             'local' => 'id',
             'foreign' => 'box_id'));
    }
}