<?php

/**
 * BaseArticleCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $article_id
 * @property CategoryArticle $CategoryArticle
 * @property Article $Article
 * 
 * @method integer         getCategoryId()      Returns the current record's "category_id" value
 * @method integer         getArticleId()       Returns the current record's "article_id" value
 * @method CategoryArticle getCategoryArticle() Returns the current record's "CategoryArticle" value
 * @method Article         getArticle()         Returns the current record's "Article" value
 * @method ArticleCategory setCategoryId()      Sets the current record's "category_id" value
 * @method ArticleCategory setArticleId()       Sets the current record's "article_id" value
 * @method ArticleCategory setCategoryArticle() Sets the current record's "CategoryArticle" value
 * @method ArticleCategory setArticle()         Sets the current record's "Article" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticleCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article_category');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CategoryArticle', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}