<?php

/**
 * BaseApiLogin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $token
 * @property timestamp $expires_at
 * @property boolean $is_active
 * @property string $latitude
 * @property string $longitude
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method string      getToken()       Returns the current record's "token" value
 * @method timestamp   getExpiresAt()   Returns the current record's "expires_at" value
 * @method boolean     getIsActive()    Returns the current record's "is_active" value
 * @method string      getLatitude()    Returns the current record's "latitude" value
 * @method string      getLongitude()   Returns the current record's "longitude" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method ApiLogin    setUserId()      Sets the current record's "user_id" value
 * @method ApiLogin    setToken()       Sets the current record's "token" value
 * @method ApiLogin    setExpiresAt()   Sets the current record's "expires_at" value
 * @method ApiLogin    setIsActive()    Sets the current record's "is_active" value
 * @method ApiLogin    setLatitude()    Sets the current record's "latitude" value
 * @method ApiLogin    setLongitude()   Sets the current record's "longitude" value
 * @method ApiLogin    setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApiLogin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('api_login');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('expires_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('latitude', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('longitude', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('user_token', array(
             'fields' => 
             array(
              0 => 'token',
             ),
             ));
        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}