<?php

/**
 * BaseActivityEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Event $Event
 * 
 * @method Event         getEvent() Returns the current record's "Event" value
 * @method ActivityEvent setEvent() Sets the current record's "Event" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivityEvent extends Activity
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'action_id',
             'foreign' => 'id'));
    }
}