<?php

/**
 * BaseAdServiceCompany
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ad_service_id
 * @property integer $company_id
 * @property enum $status
 * @property integer $crm_id
 * @property date $active_from
 * @property date $active_to
 * @property date $deal_start_date
 * @property AdService $AdService
 * @property Company $Company
 * @property CompanyOffer $CompanyOffer
 * 
 * @method integer          getAdServiceId()     Returns the current record's "ad_service_id" value
 * @method integer          getCompanyId()       Returns the current record's "company_id" value
 * @method enum             getStatus()          Returns the current record's "status" value
 * @method integer          getCrmId()           Returns the current record's "crm_id" value
 * @method date             getActiveFrom()      Returns the current record's "active_from" value
 * @method date             getActiveTo()        Returns the current record's "active_to" value
 * @method date             getDealStartDate()   Returns the current record's "deal_start_date" value
 * @method AdService        getAdService()       Returns the current record's "AdService" value
 * @method Company          getCompany()         Returns the current record's "Company" value
 * @method CompanyOffer     getCompanyOffer()    Returns the current record's "CompanyOffer" value
 * @method AdServiceCompany setAdServiceId()     Sets the current record's "ad_service_id" value
 * @method AdServiceCompany setCompanyId()       Sets the current record's "company_id" value
 * @method AdServiceCompany setStatus()          Sets the current record's "status" value
 * @method AdServiceCompany setCrmId()           Sets the current record's "crm_id" value
 * @method AdServiceCompany setActiveFrom()      Sets the current record's "active_from" value
 * @method AdServiceCompany setActiveTo()        Sets the current record's "active_to" value
 * @method AdServiceCompany setDealStartDate()   Sets the current record's "deal_start_date" value
 * @method AdServiceCompany setAdService()       Sets the current record's "AdService" value
 * @method AdServiceCompany setCompany()         Sets the current record's "Company" value
 * @method AdServiceCompany setCompanyOffer()    Sets the current record's "CompanyOffer" value
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdServiceCompany extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_service_company');
        $this->hasColumn('ad_service_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'registered',
              1 => 'paid',
              2 => 'active',
              3 => 'cancelled',
              4 => 'expired',
             ),
             'default' => 'registered',
             ));
        $this->hasColumn('crm_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('active_from', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('active_to', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('deal_start_date', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AdService', array(
             'local' => 'ad_service_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('CompanyOffer', array(
             'local' => 'id',
             'foreign' => 'ad_service_company_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}