<?php

/**
 * BasePlaceFeature
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $page_id
 * @property integer $voted_yes
 * @property integer $voted_no
 * @property integer $feature_id
 * @property Page $Page
 * @property Feature $Feature
 * @property Doctrine_Collection $PlaceFeatureVote
 * 
 * @method integer             getPageId()           Returns the current record's "page_id" value
 * @method integer             getVotedYes()         Returns the current record's "voted_yes" value
 * @method integer             getVotedNo()          Returns the current record's "voted_no" value
 * @method integer             getFeatureId()        Returns the current record's "feature_id" value
 * @method Page                getPage()             Returns the current record's "Page" value
 * @method Feature             getFeature()          Returns the current record's "Feature" value
 * @method Doctrine_Collection getPlaceFeatureVote() Returns the current record's "PlaceFeatureVote" collection
 * @method PlaceFeature        setPageId()           Sets the current record's "page_id" value
 * @method PlaceFeature        setVotedYes()         Sets the current record's "voted_yes" value
 * @method PlaceFeature        setVotedNo()          Sets the current record's "voted_no" value
 * @method PlaceFeature        setFeatureId()        Sets the current record's "feature_id" value
 * @method PlaceFeature        setPage()             Sets the current record's "Page" value
 * @method PlaceFeature        setFeature()          Sets the current record's "Feature" value
 * @method PlaceFeature        setPlaceFeatureVote() Sets the current record's "PlaceFeatureVote" collection
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlaceFeature extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('place_feature');
        $this->hasColumn('page_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('voted_yes', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('voted_no', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('feature_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Page', array(
             'local' => 'page_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Feature', array(
             'local' => 'feature_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('PlaceFeatureVote', array(
             'local' => 'id',
             'foreign' => 'place_feature_id'));
    }
}