# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_DEPRECATED)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .actions:
    login_module:           sfWpAdmin   # To be called when a non-authenticated user
    login_action:           login       # Tries to access a secure page

    secure_module:          company
    secure_action:          secure
      
  .settings:
    use_database:           true
    i18n:                   true
    default_culture:        en
    charset:                utf-8
    use_flash:              true
    standard_helpers:       [Partial, Cache, I18N, jQuery]
    
    csrf_secret:            false

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    
    enabled_modules:        [default, sfWpAdmin, sfGuardUser, sfGuardPermission, sfGuardGroup, sfJqueryTreeDoctrineManager]
