# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~
  mailer:
    param:
      delivery_strategy: realtime

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false


  mailer:
    param:
      delivery_strategy:  single_address
      delivery_address:  info@getlokal.com

dev:
  mailer:
    param:
      delivery_strategy:  single_address
      delivery_address:  info@getlokal.com


all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  user:
    class: myUser
    param:
      timeout:         1800
      logging:         %SF_LOGGING_ENABLED%
      use_flash:       true
      default_culture: %SF_DEFAULT_CULTURE%
  

  

        
  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true
      
  mailer:
    class: sfMailer
    param:
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          host:       mail.getlokal.com
          port:       25
#          username:   getlokal
#          password:   L@g0de–ºo_9

#  storage:
#    class: sfSessionStorage
#    param:
#      session_name: symfony
#      session_cookie_lifetime: 864000

  storage:
    class: sfPDOSessionStorage
    param:
      session_name:          symfony
      session_cookie_lifetime: 864000
      db_table: sessions
      database: doctrine
      db_id_col: sess_id
      db_data_col: sess_data
      db_time_col: sess_time
      
  # Save user session into DB
#  storage:
#    class: sfPDOSessionStorage
#    param:
#      session_name:          symfony
#      session_cookie_lifetime: 1800
#      db_table: session #Name of the table storing the sessions
#      database: doctrine # Name of the database connection to use
#      db_id_col: sess_id # The primary key column
#      db_data_col: sess_data # The column where the session data will be stored
#      db_time_col: sess_time # The column where the timestamp of the session will be stored