<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/12/02 09:41:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=dev.ned.local;dbname=getlokal;',
  'username' => 'getlokal',
  'password' => '3Swygyigh',
  'name' => 'doctrine',
)),);
