<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/12/02 13:58:47
$this->security = array (
  'create' => 
  array (
    'is_secure' => true,
  ),
  'edit' => 
  array (
    'is_secure' => true,
  ),
  'delete' => 
  array (
    'is_secure' => true,
  ),
  'addpagetolist' => 
  array (
    'is_secure' => true,
  ),
  'delpagefromlist' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
