<?php
// auto-generated by sfCacheConfigHandler
// date: 2014/12/02 09:41:33
$this->addCache($moduleName, '_headerLocations', array('withLayout' => false, 'lifeTime' => 86400, 'clientLifeTime' => 86400, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'recommeneded', array('withLayout' => false, 'lifeTime' => 3600, 'clientLifeTime' => 3600, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

