<?php
// auto-generated by sfCacheConfigHandler
// date: 2014/12/02 10:16:13
$this->addCache($moduleName, '_headerLocations', array('withLayout' => false, 'lifeTime' => 86400, 'clientLifeTime' => 86400, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, '_content', array('withLayout' => false, 'lifeTime' => 8640000, 'clientLifeTime' => 8640000, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

