<?php
// auto-generated by sfCacheConfigHandler
// date: 2014/12/02 09:41:27
$this->addCache($moduleName, '_headerLocations', array('withLayout' => false, 'lifeTime' => 86400, 'clientLifeTime' => 86400, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, '_related_classifications', array('withLayout' => false, 'lifeTime' => 3600, 'clientLifeTime' => 3600, 'contextual' => true, 'vary' => array ()));
$this->addCache($moduleName, '_top_places', array('withLayout' => false, 'lifeTime' => 3600, 'clientLifeTime' => 3600, 'contextual' => true, 'vary' => array ()));
$this->addCache($moduleName, 'directory', array('withLayout' => false, 'lifeTime' => 172800, 'clientLifeTime' => 172800, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'locations', array('withLayout' => false, 'lifeTime' => 7200, 'clientLifeTime' => 7200, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'sublevel', array('withLayout' => false, 'lifeTime' => 7200, 'clientLifeTime' => 7200, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, '_feed', array('withLayout' => false, 'lifeTime' => 7200, 'clientLifeTime' => 7200, 'contextual' => true, 'vary' => array ()));
$this->addCache($moduleName, '_related_classificationsWide', array('withLayout' => false, 'lifeTime' => 7200, 'clientLifeTime' => 7200, 'contextual' => true, 'vary' => array ()));
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

