<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/12/02 10:13:24
$this->security = array (
  'create' => 
  array (
    'is_secure' => true,
  ),
  'edit' => 
  array (
    'is_secure' => true,
  ),
  'delete' => 
  array (
    'is_secure' => true,
  ),
  'addeventuser' => 
  array (
    'is_secure' => true,
  ),
  'setevent' => 
  array (
    'is_secure' => true,
  ),
  'deleteimage' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
