<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/12/02 10:16:13
$this->security = array (
  'create' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'article_writer',
        1 => 'article_editor',
        2 => 'admin',
      ),
    ),
  ),
  'edit' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'article_writer',
        1 => 'article_editor',
        2 => 'admin',
      ),
    ),
  ),
  'delete' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
  'addpagetoarticle' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'article_editor',
        1 => 'admin',
      ),
    ),
  ),
  'delpagefromarticle' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'article_editor',
        1 => 'admin',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
