<?php

/**
 * ActivityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Activity');
    }
    
    public function getActivity($id)
    {
      if(!$return = $this->findOneByActionId($id))
      {
        $class = $this->getClassnameToReturn();
        $return = new $class;
        $return->setActionId($id);
      }
      return $return;
    }
}