<?php

/**
 * ActivityListPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityListPageTable extends ActivityTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityListPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityListPage');
    }
}