<?php

/**
 * ActivityReviewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityReviewTable extends ActivityTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityReviewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityReview');
    }
}