<?php

/**
 * AdminRememberKeyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdminRememberKeyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdminRememberKeyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdminRememberKey');
    }
}