<?php

/**
 * AdServiceCompany
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AdServiceCompany extends BaseAdServiceCompany
{
   public function getDealServiceToActivate() {
		$query = Doctrine::getTable ( 'AdServiceCompany' )
		->createQuery ( 'adc' )
		->where('adc.id = ?', $this->getId())
		->andWhere('adc.status = "paid" AND adc.ad_service_id =13')		
		->andWhere('((adc.active_to is null AND adc.crm_id is not null) OR (adc.active_to >= '.ProjectConfiguration::nowAlt().' AND  adc.crm_id is null)) ');
         
		
		$service_to_active =  $query->fetchOne();
		
		return $service_to_active;
	}
}