<?php

/**
 * AdServiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdServiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdServiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdService');
    }
    const CLASSIFICATIONS_COUNT = 4;
    const VIDEO_COUNT = 5;
}