<?php

/**
 * AdServiceCompanyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdServiceCompanyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdServiceCompanyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdServiceCompany');
    }
}