<?php

/**
 * ArticlePageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticlePageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticlePageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticlePage');
    }
}