<?php

/**
 * ArticleEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleEventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticleEvent');
    }
}