<?php

/**
 * BadgeRequirementFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BadgeRequirementFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BadgeRequirementFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BadgeRequirementField');
    }
}