<?php

/**
 * BoxToZoneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BoxToZoneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BoxToZoneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BoxToZone');
    }
}