<?php

/**
 * BoxToZone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BoxToZone extends BaseBoxToZone
{
  public function getSettings()
  {
    $settings = is_array($this->_get('settings'))? $this->_get('settings'): array($this->_get('settings'));
    
    return sfToolkit::arrayDeepMerge($this->getBox()->getSettings(), $settings);
  }
  
  public function setSettings($v)
  {
    foreach($v as $key=>$val)
      if(is_null($val)) unset($v[$key]);
      
    $this->_set('settings', $v);
  }
  
  public function getModule()
  {
    return $this->getBox()->getModule();
  }
  
  public function getComponent()
  {
    return $this->getBox()->getComponent();
  }
  
  public function getStringSettings()
  {
    return base64_encode(serialize($this->getSettings()));
  }
}