<?php

/**
 * CategoryClassificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryClassificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryClassificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryClassification');
    }
}