<?php

/**
 * CategoryArticleClassificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryArticleClassificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryArticleClassificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryArticleClassification');
    }
}