<?php

/**
 * CategoryArticleCountryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryArticleCountryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryArticleCountryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryArticleCountry');
    }
}