<?php

/**
 * CategorySectorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategorySectorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategorySectorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategorySector');
    }
}