<?php

/**
 * CheckInTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CheckInTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CheckInTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CheckIn');
    }
}