<?php

/**
 * CityTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('City');
    }

    public function getCityNames($culture = null)
    {
        
        if (!$culture) {
            $culture = sfContext::getInstance()->getUser()->getCulture();
        }

        $query = Doctrine_Core::getTable('City')
            ->createQuery('q')
            ->innerJoin('.Translation ct')
            ->orderBy('name ASC');
        return $query->execute();
    }

    public static function defaultCitiesQuery($country_id = null)
    {
        $query = self::getInstance()->createQuery('c')
            ->where('is_default > 0');
        
        if (!is_null($country_id)) {
            $query = $query
                ->innerJoin('c.County co')
                ->addWhere('co.country_id = ?', $country_id);
        }

        return $query;
    }

    public static function getByAddress($address, $country_id = null)
    {
        $tmp = explode(',', $address);
        $search_city = trim(array_shift($tmp));
        $search_country = trim(array_pop($tmp));

        $query = Doctrine::getTable('City')
                ->createQuery('c')
                ->innerJoin('c.County co')
                ->innerJoin('c.Translation ct')
                ->where('ct.name = ?', $search_city);
        if ($country_id) {
             $query->addWhere('co.country_id = ?', $country_id);
        } else {
            $query->innerJoin('co.Country cty')
                    ->addWhere('cty.name = ? OR cty.name_en = ?', array($search_country, $search_country));
        }

        return $query->fetchOne();
    }

    public static function getAutocompleteJSON($term, $exclude = array(), $country_id = null)
    {
        $term = '%' . $term . '%';
        $query = self::getInstance()->createQuery('c')
            ->select('c.id, ct.name')
            ->innerJoin('c.Translation ct')
            ->whereNotIn('c.id', $exclude)
            ->addWhere('ct.name LIKE ?', $term);

        if (!is_null($country_id)) {
            $query->innerJoin('c.County co')->addWhere('co.country_id = ?', $country_id);
        }

        $cities = $query->execute();
        $data = array();
        foreach ($cities as $c) {
            $data[] = array(
                'label' => $c->getName(),
                'value' => $c->getName(),
                'id' => $c->getId()
            );
        }

        return $data;
    }

    public static function findOrCreate($city, $county, $country, $lat = null, $lng = null)
    {
        // find the city in that country
        $cityTerm = "{$city}";
        $countyTerm = "{$county}";
        $countryTerm = "{$country}";

        if (!$country) {
            return null;
        }
        $query = self::getInstance()->createQuery('c')
            ->innerJoin('c.Translation ct')
            ->innerJoin('c.County co')
            ->innerJoin('co.Country cou')
            ->where('ct.name LIKE ?', $cityTerm)
            // ->andWhere('co.name LIKE ?', array($countyTerm))
            ->andWhere('cou.name LIKE ? OR cou.name_en LIKE ?', array($countryTerm, $countryTerm));
        
        if ($query->count() > 0) {
            $c = $query->fetchOne();
        } else {          
            $cult = sfContext::getInstance()->getUser()->getCulture();  
            sfContext::getInstance()->getUser()->setCulture('en');
            $county = CountyTable::findOrCreate($county, $country);
            $partnerClass = getlokalPartner::getLanguageClass();
            
            if ($county->getCountry()->getSlug()) {
                $partnerClass = strtolower($county->getCountry()->getSlug());
            }
            
            $c = new City();
            $c->setName($city);
            $c->setCounty($county);
            $c->setLat($lat);
            $c->setLng($lng);
            $c->setSlug(self::slugify($c->getName()));
            $c->save();
            sfContext::getInstance()->getUser()->setCulture($cult);
        }
        
        return $c;
    }

    public static function geocodeUrl($address = null, $lat = null, $lng = null, $addressPrior = false) {
        $url = null;
        if ($addressPrior) {
            if (!empty($address)) {
                $address = urlencode($address);
                $url = "address={$address}";
            } elseif (!empty($lat) && !empty($lng)) {
                $url = "latlng={$lat},{$lng}";
            }
        } else {
            if (!empty($lat) && !empty($lng)) {
                $url = "latlng={$lat},{$lng}";
            } elseif (!empty($address)) {
                $address = urlencode($address);
                $url = "address={$address}";
            }
        }

        return $url;
    }

    public static function slugify($str, $options = array()) {
        // Make sure string is in UTF-8 and strip invalid UTF-8 characters
        $str = mb_convert_encoding((string)$str, 'UTF-8', mb_list_encodings());

        $defaults = array(
            'delimiter' => '-',
            'limit' => null,
            'lowercase' => true,
            'replacements' => array(),
            'transliterate' => true,
        );

        // Merge options
        $options = array_merge($defaults, $options);

        $char_map = array(
            // Latin
            'À' => 'A', 'Á' => 'A', 'Â' => 'A', 'Ã' => 'A', 'Ä' => 'A', 'Å' => 'A', 'Æ' => 'AE', 'Ç' => 'C',
            'È' => 'E', 'É' => 'E', 'Ê' => 'E', 'Ë' => 'E', 'Ì' => 'I', 'Í' => 'I', 'Î' => 'I', 'Ï' => 'I',
            'Ð' => 'D', 'Ñ' => 'N', 'Ò' => 'O', 'Ó' => 'O', 'Ô' => 'O', 'Õ' => 'O', 'Ö' => 'O', 'Ő' => 'O',
            'Ø' => 'O', 'Ù' => 'U', 'Ú' => 'U', 'Û' => 'U', 'Ü' => 'U', 'Ű' => 'U', 'Ý' => 'Y', 'Þ' => 'TH',
            'ß' => 'ss',
            'à' => 'a', 'á' => 'a', 'â' => 'a', 'ã' => 'a', 'ä' => 'a', 'å' => 'a', 'æ' => 'ae', 'ç' => 'c',
            'è' => 'e', 'é' => 'e', 'ê' => 'e', 'ë' => 'e', 'ì' => 'i', 'í' => 'i', 'î' => 'i', 'ï' => 'i',
            'ð' => 'd', 'ñ' => 'n', 'ò' => 'o', 'ó' => 'o', 'ô' => 'o', 'õ' => 'o', 'ö' => 'o', 'ő' => 'o',
            'ø' => 'o', 'ù' => 'u', 'ú' => 'u', 'û' => 'u', 'ü' => 'u', 'ű' => 'u', 'ý' => 'y', 'þ' => 'th',
            'ÿ' => 'y',

            // Latin symbols
            '©' => '(c)',

            // Greek
            'Α' => 'A', 'Β' => 'B', 'Γ' => 'G', 'Δ' => 'D', 'Ε' => 'E', 'Ζ' => 'Z', 'Η' => 'H', 'Θ' => '8',
            'Ι' => 'I', 'Κ' => 'K', 'Λ' => 'L', 'Μ' => 'M', 'Ν' => 'N', 'Ξ' => '3', 'Ο' => 'O', 'Π' => 'P',
            'Ρ' => 'R', 'Σ' => 'S', 'Τ' => 'T', 'Υ' => 'Y', 'Φ' => 'F', 'Χ' => 'X', 'Ψ' => 'PS', 'Ω' => 'W',
            'Ά' => 'A', 'Έ' => 'E', 'Ί' => 'I', 'Ό' => 'O', 'Ύ' => 'Y', 'Ή' => 'H', 'Ώ' => 'W', 'Ϊ' => 'I',
            'Ϋ' => 'Y',
            'α' => 'a', 'β' => 'b', 'γ' => 'g', 'δ' => 'd', 'ε' => 'e', 'ζ' => 'z', 'η' => 'h', 'θ' => '8',
            'ι' => 'i', 'κ' => 'k', 'λ' => 'l', 'μ' => 'm', 'ν' => 'n', 'ξ' => '3', 'ο' => 'o', 'π' => 'p',
            'ρ' => 'r', 'σ' => 's', 'τ' => 't', 'υ' => 'y', 'φ' => 'f', 'χ' => 'x', 'ψ' => 'ps', 'ω' => 'w',
            'ά' => 'a', 'έ' => 'e', 'ί' => 'i', 'ό' => 'o', 'ύ' => 'y', 'ή' => 'h', 'ώ' => 'w', 'ς' => 's',
            'ϊ' => 'i', 'ΰ' => 'y', 'ϋ' => 'y', 'ΐ' => 'i',

            // Turkish
            'Ş' => 'S', 'İ' => 'I', 'Ç' => 'C', 'Ü' => 'U', 'Ö' => 'O', 'Ğ' => 'G',
            'ş' => 's', 'ı' => 'i', 'ç' => 'c', 'ü' => 'u', 'ö' => 'o', 'ğ' => 'g',

            // Russian
            'А' => 'A', 'Б' => 'B', 'В' => 'V', 'Г' => 'G', 'Д' => 'D', 'Е' => 'E', 'Ё' => 'Yo', 'Ж' => 'Zh',
            'З' => 'Z', 'И' => 'I', 'Й' => 'J', 'К' => 'K', 'Л' => 'L', 'М' => 'M', 'Н' => 'N', 'О' => 'O',
            'П' => 'P', 'Р' => 'R', 'С' => 'S', 'Т' => 'T', 'У' => 'U', 'Ф' => 'F', 'Х' => 'H', 'Ц' => 'C',
            'Ч' => 'Ch', 'Ш' => 'Sh', 'Щ' => 'Sh', 'Ъ' => '', 'Ы' => 'Y', 'Ь' => '', 'Э' => 'E', 'Ю' => 'Yu',
            'Я' => 'Ya',
            'а' => 'a', 'б' => 'b', 'в' => 'v', 'г' => 'g', 'д' => 'd', 'е' => 'e', 'ё' => 'yo', 'ж' => 'zh',
            'з' => 'z', 'и' => 'i', 'й' => 'j', 'к' => 'k', 'л' => 'l', 'м' => 'm', 'н' => 'n', 'о' => 'o',
            'п' => 'p', 'р' => 'r', 'с' => 's', 'т' => 't', 'у' => 'u', 'ф' => 'f', 'х' => 'h', 'ц' => 'c',
            'ч' => 'ch', 'ш' => 'sh', 'щ' => 'sh', 'ъ' => '', 'ы' => 'y', 'ь' => '', 'э' => 'e', 'ю' => 'yu',
            'я' => 'ya',

            // Ukrainian
            'Є' => 'Ye', 'І' => 'I', 'Ї' => 'Yi', 'Ґ' => 'G',
            'є' => 'ye', 'і' => 'i', 'ї' => 'yi', 'ґ' => 'g',

            // Czech
            'Č' => 'C', 'Ď' => 'D', 'Ě' => 'E', 'Ň' => 'N', 'Ř' => 'R', 'Š' => 'S', 'Ť' => 'T', 'Ů' => 'U',
            'Ž' => 'Z',
            'č' => 'c', 'ď' => 'd', 'ě' => 'e', 'ň' => 'n', 'ř' => 'r', 'š' => 's', 'ť' => 't', 'ů' => 'u',
            'ž' => 'z',

            // Polish
            'Ą' => 'A', 'Ć' => 'C', 'Ę' => 'e', 'Ł' => 'L', 'Ń' => 'N', 'Ó' => 'o', 'Ś' => 'S', 'Ź' => 'Z',
            'Ż' => 'Z',
            'ą' => 'a', 'ć' => 'c', 'ę' => 'e', 'ł' => 'l', 'ń' => 'n', 'ó' => 'o', 'ś' => 's', 'ź' => 'z',
            'ż' => 'z',

            // Latvian
            'Ā' => 'A', 'Č' => 'C', 'Ē' => 'E', 'Ģ' => 'G', 'Ī' => 'i', 'Ķ' => 'k', 'Ļ' => 'L', 'Ņ' => 'N',
            'Š' => 'S', 'Ū' => 'u', 'Ž' => 'Z',
            'ā' => 'a', 'č' => 'c', 'ē' => 'e', 'ģ' => 'g', 'ī' => 'i', 'ķ' => 'k', 'ļ' => 'l', 'ņ' => 'n',
            'š' => 's', 'ū' => 'u', 'ž' => 'z'
        );

        // Make custom replacements
        $str = preg_replace(array_keys($options['replacements']), $options['replacements'], $str);

        // Transliterate characters to ASCII
        if ($options['transliterate']) {
            $str = str_replace(array_keys($char_map), $char_map, $str);
        }

        // Replace non-alphanumeric characters with our delimiter
        $str = preg_replace('/[^\p{L}\p{Nd}]+/u', $options['delimiter'], $str);

        // Remove duplicate delimiters
        $str = preg_replace('/(' . preg_quote($options['delimiter'], '/') . '){2,}/', '$1', $str);

        // Truncate slug to max. characters
        $str = mb_substr($str, 0, ($options['limit'] ? $options['limit'] : mb_strlen($str, 'UTF-8')), 'UTF-8');

        // Remove delimiter from ends
        $str = trim($str, $options['delimiter']);
        $str = myTools::replaceDiacritics($str);
        return $options['lowercase'] ? mb_strtolower($str, 'UTF-8') : $str;

    }

    public static function createFromGeocode($data, $setUser = true) {
        // if city and country are found and current city not set than find the city and country in db or add them
        $city = null;
        $user = sfContext::getInstance()->getUser();
        $cu = $user->getCulture();
            
        if(isset($data['city_en']) && isset($data['country_en'])) {
            if($data['county_en'] === null) {
                $data['county_en'] = $data['city_en'];
            }
                
            $city = CityTable::findOrCreate(
                        $data['city_en'], $data['county_en'], $data['country_en'],
                        $data['latitude'], $data['longitude']
                    );
        
            if ($setUser) {
                $sf_user = sfContext::getInstance()->getUser();
                if ($sf_user) {
                    $sf_user->setCity($city);
                }
            }
            
        }

        return $city;
    }


}
