<?php

/**
 * ClassificationSectorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClassificationSectorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClassificationSectorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClassificationSector');
    }
}