<?php

/**
 * Comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Comment extends BaseComment
{
	
  public function preSave($event)
  {    
    $count = Doctrine::getTable('Comment')
              ->createQuery('c')
              ->where('c.activity_id = ?', $this->getActivityId())
              ->count();
              
    $this->setRank($count + 1);
    $this->setBody(strip_tags($this->getBody()));
  }
  
  public function postSave($event)
  {    
    /*$count = Doctrine::getTable('Comment')
              ->createQuery('c')
              ->where('c.activity_id = ?', $this->getActivityId())
              ->count();*/
              
    $activity = $this->getActivity();
    $activity->setCommentCount($this->getRank());
    $activity->clearRelated();
    $activity->save();
    
    $activityc = Doctrine::getTable('ActivityComment')->getActivity($this->getId());
    $activityc->setText($this->getBody());
    $activityc->setCaption($activity->getCaption());
    $activityc->setUserId($this->getUserId());
    $activityc->setMediaId($activity->getMediaId());
    $activityc->setActivityId($activity->getId());
    $activityc->save();
  }
}