<?php

/**
 * CompanyLocation
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CompanyLocation extends BaseCompanyLocation {

    public static $street_types = array(
        1 => 'Blvd',
        2 => 'Qtr',
        3 => 'N\'hood',
        4 => 'Area',
        5 => 'Sq.',
        6 => 'Str.',
        7 => 'PO Box',
        8 => 'Zone',
        10 => 'Cal',
        11 => 'Prel',
        14 => 'Drum',
        15 => 'Int',
        16 => 'Fdt',
        17 => 'Şos',
        18 => 'Al'
    );

    public function postSave($event) {
        parent::postSave($event);
        $company = $this->getCompany();
        $company->save();
    }

    public function getLatitude() {
        return $this->_get('latitude') > 0 ? $this->_get('latitude') : $this->getCompany()->getCity()->getLat();
    }

    public function getLongitude() {
        return $this->_get('longitude') > 0 ? $this->_get('longitude') : $this->getCompany()->getCity()->getLng();
    }


    public static function getStreetTypeStringById($id) {    	
    	return sfContext::getInstance()->getI18N()->__(self::$street_types[$id]);
    }
    
    public function __toString() {
        $return = '';

        if ($this->getStreetTypeId()) {
            $return .= ' ' . self::$street_types[$this->getStreetTypeId()];
        }
        if ($this->getStreet()) {
            $return .= ' ' . $this->getStreet();
        }
        if ($this->getStreetNumber()) {
            $no = sfContext::getInstance()->getI18N()->__('No.');
            $return .= ' ' . $no . ' ' . $this->getStreetNumber();
        }
        if ($this->getAppartment()) {
            $no = sfContext::getInstance()->getI18N()->__('Ap.');
            $return .= ' ' . $no . ' ' . $this->getAppartment();
        }

        return (string) $return;
    }

    public function save(Doctrine_Connection $conn = null) {
        if ($this->getCompany() && $this->getCompany()->getFollowers(true)) {
            if (! $this->isNew()) {
                $modified = $this->getModified(true );

                if (
                    isset($modified['street_number']) ||
                    isset($modified['street']) ||
                    isset($modified['neighbourhood']) ||
                    isset($modified['building_no']) ||
                    isset($modified['entrance'])
                ) {
                    $activity = new ActivityPage();
                    $activity->setText($this->getCompany()->getCompanyTitle());
                    $activity->setModifiedField('location');
                    $activity->setPageId($this->getCompany()->getCompanyPage()->getId());
                    $activity->setUserId($this->getUserId());
                    if ($this->getCompany()->getImage()) {
                        $activity->setMediaId($this->getCompany()->getImageId());
                    }
                    $activity->save();
                }

            }
        }
        return parent::save($conn);
    }

}
