<?php

/**
 * CompanyFeatureCompanyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompanyFeatureCompanyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompanyFeatureCompanyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompanyFeatureCompany');
    }
}