<?php

/**
 * CompanyClassificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompanyClassificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompanyClassificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompanyClassification');
    }
    
 public  static function getObjectByCompanyId($company_id)
    {
 	
 	$query = Doctrine_Core::getTable ( 'CompanyClassification' )
 	->createQuery ( 'co1' )
 	->innerJoin('co1.Classification co2')
 	 ->leftJoin('co1.CompanyProductClassification cp1')
      ->where('co1.company_id = ?', $company_id);
       
      $q3 = $query->createSubquery ()->select ( 'cpo.foreign_id' )
            ->from ( 'CompanyProductClassification cpo' )
            ->innerJoin('cpo.CompanyClassification co')           
            ->andWhere ( 'co.company_id = ?' , $company_id );
      
       $q4 = $query->createSubquery ()->select ( 'ccc.id' )
      ->from ( 'Company c' )
      ->innerJoin('c.CompanyClassification ccc')
      ->andWhere('ccc.classification_id = c.classification_id');      
            
     $query->andWhere ( 'co1.id NOT IN (' . $q3->getDql () . ')' );  
     $query->andWhere ( 'co1.id NOT IN (' . $q4->getDql () . ')' );
     
      $classifications = $query->execute();
      
     
     return $classifications; 
 }
}