<?php

/**
 * CompanyClassification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CompanyClassification extends BaseCompanyClassification {
	
	public function postSave($event) {
		parent::postSave ( $event );
		$company = $this->getCompany ();
		$company->save ();
	}
	public function save(Doctrine_Connection $conn = null) {
		if ($this->getCompany ()->getFollowers ( true )) {
			if (! $this->isNew ()) {
				
				$modified = $this->getModified ( true );
				
				if (isset ( $modified ['classification_id'] )) {
					$activity = new ActivityPage ();
					$activity->setText ( $this->getCompany ()->getCompanyTitle () );
					$activity->setModifiedField ( 'classification' );
					$activity->setPageId ( $this->getCompany ()->getCompanyPage ()->getId () );
					$activity->setUserId ( sfContext::getInstance ()->getUser ()->getGuardUser ()->getId () );
					if ($this->getCompany ()->getImage ()) {
						$activity->setMediaId ( $this->getCompany ()->getImageId () );
					}
					$activity->save ();
				
				}
			}
		}
		return parent::save ( $conn );
	}
}