<?php

/**
 * Conversation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Conversation extends BaseConversation
{
public function setNewMessage(Message $v = null)
  {
  
    if($v === null) return;
    
    $msg = clone $v;
    $this->setOpened(true);
    $this->save();
    $v->setConversation($this);
    $v->setIsRead(true);
    $v->save();
    $this->setLastMessageId($v->getId());
    $this->save();
    
 
    $conversation = Doctrine::getTable('Conversation')->getConversation($this->getToPage(), $this->getFromPage());
    $conversation->save();
    $conversation->setOpened(false);
    $msg->setConversation($conversation);
    $msg->save();
    $conversation->setLastMessageId($msg->getId());
    $conversation->save();
  
  }
  
  public function getPage()
  {
    return $this->getToPage();
  } 
}