<?php

/**
 * Country
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Country extends BaseCountry {
	
    public function getDefaultCities() {
        $q = Doctrine::getTable('City')
            ->createQuery('c')
            ->innerJoin('c.County co')
            ->innerJoin('co.Country cou')
            ->innerJoin('c.Translation ct')
            ->where('co.country_id = ?', $this->getId())
            ->andWhere('c.is_default > 0')
            ->andWhere('ct.lang = ?',sfContext::getInstance()->getUser()->getCulture())
            ->orderBy('c.is_default DESC');
        $relations_array = array(
        	'City'=>'County',
        	'County'=>'Country'
        );
        $q->useResultCache(true, 3600, "country_default_cities_".serialize($q->getCountQueryParams()),$relations_array);
        $cities = $q->execute();
        
        return $cities;
    }

    public function getI18nName($culture = null) {
        $name = $this->getName();
        $name_en = $this->getNameEn();
        if (!$culture) {
            $culture = sfContext::getInstance()->getUser()->getCulture();
        }
        if ($culture == 'en') {
            return $name_en;
        }
        if ($culture == $this->getSlug() && !empty($name)) {
            return $name;
        }
        return $name_en;
    }

    public function getCountryNameByCulture($culture = null) {
        return $this->getI18nName($culture);
        // if (!$culture) {
        //     $culture = sfContext::getInstance()->getUser()->getCulture();
        // }
        // if ($culture == 'en') {
        //     if ($this->getNameEn()) {
        //         return $this->getNameEn();
        //     }
        //     else {
        //         return $this->getName();
        //     }
        // } else {
        //     if ($this->getName()) {
        //         return $this->getName();
        //     }
        //     else {
        //         return $this->getNameEn();
        //     }
        // }
    }

    public function getLocation($culture) {
        if (!$culture) {
            $culture = sfContext::getInstance()->getUser()->getCulture();
        }
        
        if ($culture == $this->getSlug() && $this->getName()) {
            return $this->getName();
        }
        else {
            return $this->getNameEn();
        }
    }
	
}
