<?php

/**
 * CubesLogin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CubesLogin extends BaseCubesLogin
{
 public function preInsert($event)
  {
    $this->token = md5(uniqid($this->getUserId()));
    $this->setExpiresAt(date('Y-m-d H:i:s', time() + (30* 86400)));
    
    parent::preInsert($event);
  }
}