<?php

/**
 * EventPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventPage');
    }
}