<?php

/**
 * EventSearchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventSearchTable extends SearchTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventSearchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventSearch');
    }
}