<?php
 
/**
 * FacebookReviewGameResultTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacebookReviewGameResultTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacebookReviewGameResultTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FacebookReviewGameResult');
    }
}