<?php

/**
 * FeatureCompanyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeatureCompanyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FeatureCompanyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FeatureCompany');
    }
}