<?php

/**
 * FollowTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FollowTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FollowTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Follow');
    }
}