<?php

/**
 * getWeekendEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class getWeekendEventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object getWeekendEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('getWeekendEvent');
    }
}