<?php

/**
 * ImageReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImageReportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImageReportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ImageReport');
    }
}