<?php

/**
 * LikeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LikeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LikeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Like');
    }
}