<?php

/**
 * Menu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Menu extends BaseMenu
{       
	public function getPath() {
		return sfConfig::get('sf_upload_dir') . DIRECTORY_SEPARATOR . 'menus' . DIRECTORY_SEPARATOR . $this->getFilename();
	}
	public function getPublicPath() {
		return public_path('uploads' . DIRECTORY_SEPARATOR . 'menus' . DIRECTORY_SEPARATOR . $this->getFilename());
	}
	public function getDownloadLink($text = "Download", $param = null) {
		return link_to($text, $this->getPublicPath(), $param);
	}
}
