<?php

/**
 * MobileLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MobileLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MobileLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MobileLog');
    }
}