<?php

/**
 * MobileNotificationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MobileNotificationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MobileNotificationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MobileNotifications');
    }
}