<?php

/**
 * PilotVoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PilotVoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PilotVoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PilotVote');
    }
}