<?php

/**
 * PilotVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PilotVideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PilotVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PilotVideo');
    }
}