<?php

/**
 * PlaceFeatureVoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlaceFeatureVoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlaceFeatureVoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlaceFeatureVote');
    }
}