<?php

/**
 * ReportReviewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReportReviewTable extends ReportTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReportReviewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReportReview');
    }
}