<?php

/**
 * ReportCompanyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReportCompanyTable extends ReportTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReportCompanyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReportCompany');
    }
}