<?php

/**
 * ReviewTopWeekTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReviewTopWeekTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReviewTopWeekTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReviewTopWeek');
    }
}