<?php

/**
 * ReviewVoucherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReviewVoucherTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReviewVoucherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReviewVoucher');
    }
}