<?php

/**
 * ReviewSearchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReviewSearchTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReviewSearchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReviewSearch');
    }
}