<?php

/**
 * SectorFeatureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SectorFeatureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SectorFeatureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SectorFeature');
    }
}