<?php

/**
 * SerbianCitiesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SerbianCitiesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SerbianCitiesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SerbianCities');
    }
}