<?php

/**
 * SitemapsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SitemapsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SitemapsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sitemaps');
    }
}