<?php

/**
* StaticPageTable
*
* This class has been auto-generated by the Doctrine ORM Framework
*/
class StaticPageTable extends Doctrine_Table
{
    /**
    * Returns an instance of this class.
    *
    * @return object StaticPageTable
    */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StaticPage');
    }

    protected function UriDomain($uri = null)
    {

    }

    public function findOneBySlug($slug) {
        $culture = sfContext::getInstance()->getUser()->getCulture();
        $query = self::getInstance()->createQuery('sp')
            ->innerJoin('sp.Translation t')
            ->where('t.lang = ?', $culture)
            ->andWhere('t.slug = ?', $slug)
            ->andWhere('t.is_active = 1')
            ->addWhere('sp.country_id = ?', getlokalPartner::getInstance());

        return $query->fetchOne();
    }

    public static function findSlugById($id) {
        $culture = sfContext::getInstance()->getUser()->getCulture();

        $partner_id = getlokalPartner::getInstance();
        $query = Doctrine_Core::getTable('StaticPage')
            ->createQuery('sp')
            ->leftJoin('sp.Translation t')
            ->where('t.lang = ?', $culture)
            ->andWhere('sp.id = ?', $id)
            ->andWhere('sp.country_id = ?', $partner_id)
            ->andWhere('sp.status = ?', 'approved');

        $sp = $query->fetchOne() ;

        return $sp->getSlug();
    }

}
