<?php

/**
* StaticPage
*
* This class has been auto-generated by the Doctrine ORM Framework
*
* @package    getLokal
* @subpackage model
* @author     Get Lokal
* @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
*/
class StaticPage extends BaseStaticPage {

    public function findAll()
    {
        $culture = sfContext::getInstance()->getUser()->getCulture();
        $partner_id = getlokalPartner::getInstance();
        return Doctrine_Query::create()
            ->select('sp.id, t.title, t.content, t.slug, t.is_active')
            ->from('StaticPage sp')
            ->leftJoin('sp.Translation t')
            ->where('t.lang = ?', $culture)
            ->andWhere('sp.country_id = ?', $partner_id)->execute();
    }

    public function getParentId()
    {
        if (!$this->getNode()->isValidNode() || $this->getNode()->isRoot()) {
            return null;
        }

        $parent = $this->getNode()->getParent();

        return $parent['id'];
    }

    public function getParent()
    {
        if ($this->getNode()->hasParent()) {
            return $this->getNode()->getParent();
        }
        return null;
    }

    // public function save(Doctrine_Connection $conn = null)
    // {
    //     parent::save($conn);
    //     // var_dump($this->_values); die;
    // }

}
