<?php

/**
 * UrlMapTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UrlMapTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UrlMapTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UrlMap');
    }
}