<?php

/**
 * UserBadge
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    getLokal
 * @subpackage model
 * @author     Get Lokal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserBadge extends BaseUserBadge
{
  public function postSave($event)
  {
    parent::postSave($event);
    
    $users = Doctrine::getTable('UserProfile')->count();
    
    $count = Doctrine::getTable('UserBadge')
              ->createQuery('b')
              ->where('b.badge_id = ?', $this->getBadgeId())
              ->count();
              
    $proc = round(($count / $users) * 100, 2);
    
    $badge = $this->getBadge();
    $badge->setPercent($proc);
    $badge->save();
  }

  public function postInsert($event)
  {
  	 parent::postSave ( $event );	
  	 sfProjectConfiguration::getActive()->getEventDispatcher()->notify(new sfEvent($this, 'social.badge_won'));
  }

}