<?php

/**
 * VoucherTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VoucherTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VoucherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Voucher');
    }

    public static function getVouchersQuery($user=false, $offer=false, $is_valid = false)
    {
        $today = date('Y-m-d');
        $query = Doctrine_Core::getTable('Voucher')->createQuery('a')
            ->innerJoin('a.CompanyOffer co')
            ->orderBy('a.id DESC');

        if ($user) {
            $query->addWhere('a.user_id = ?', $user->getId());
        }
        if ($offer) {
            $query->andWhere('co.id = ?', $offer->getId());
        }
        if ($is_valid) {
            $query->andWhere('co.valid_from <= ?', $today)
                ->andWhere('co.valid_to >= ?', $today);
        }

        return $query;
    }

    public static function getVouchers($user=false, $offer=false, $is_valid = false)
    {
        $query = self::getVouchersQuery($user, $offer, $is_valid);
        return $query->execute();
    }

    public static function getVouchersCount($user=false, $offer=false, $is_valid = false)
    {
        $query = self::getVouchersQuery($user, $offer, $is_valid );
        $vouchers = $query->execute();
        return count($vouchers);
    }
}
