# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings 1.1

prod:
  .settings:
    error_reporting:        <?php echo E_ALL."\n" ?>
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_DEPRECATED)."\n" ?>
    web_debug:              true
    cache:                  true
    no_script_name:         false
    etag:                   false
    logging_enabled:        true

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    use_database:           true
    i18n:                   true
    cache:                  true
    charset:                utf-8
    use_flash:              true
    standard_helpers:       [Partial, Cache, I18N, Breadcrumb, Text, Frontend]
    # Form security secret (CSRF protection)
    csrf_secret:            915037acb955c5e21f67cc07a4cf468c088ed884

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    enabled_modules:        [sfGuardAuth,sfCaptchaGD]
    
    login_module:           user
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure
   
    default_culture:        bg
  .actions:
    error_404_module:       home
    error_404_action:       error404   
    error_403_module:       home
    error_403_action:       error403  
