generator:
  class: sfDoctrineGenerator
  param:
    model_class:           UnregisteredNewsletterUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          unregistered_newsletter_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        max_per_page:  15
      filter:   
        display:  [firstname, lastname, email_address]
      form:    ~
      edit:    ~
      new:     ~
