generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Classification
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          classification
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
      list:
        display:       [ id, title, crm_id, keywords]
        object_actions:
          _edit:      ~
          _delete:    ~
          updateCount:     { label: Update Place Count, action: updateCount }      
      filter:  
        display:       [ id, title, keyword, sector_id, crm_id]
      form:    
        class:  backendClassificationForm
      edit:    ~
      new:     ~
