default:
  is_secure: true
  credentials: [[classification_bg, classification_ro, classification_sr, classification_mk, classification_fi, classification_me, classification_ru]]
logout:
    is_secure: false