all:
  stylesheets: [ -*, //ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/themes/ui-lightness/jquery-ui.css]
  javascripts: [ -*, //ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js, //ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/jquery-ui.min.js ]
  
game1Success:
  stylesheets: [ //www.getlokal.com/css/facebook/game1.css ]

game1bgSuccess:
  stylesheets: [ //www.getlokal.com/css/facebook/game1bg.css ]

game1Done:
  stylesheets: [ //www.getlokal.com/css/facebook/game1.css ]

game1bgDone:
  stylesheets: [ //www.getlokal.com/css/facebook/game1bg.css ]

reviewSuccess:
  stylesheets: [ /css/facebook/game2.css, /css/facebook/game2sr.css ]
  
reviewDone:
  stylesheets: [ /css/facebook/game2.css, /css/facebook/game2sr.css ]

# Big racing (BG)
game2bgSuccess:
  javascripts: [-*, //www.getlokal.com/js/jquery.js, //www.getlokal.com/js/jquery-ui.js, //www.getlokal.com/js/jquery.tinyscrollbar.min.js ]
  stylesheets: [ //www.getlokal.com/css/jquery.rating.css, //www.getlokal.com/sfFormExtraPlugin/css/jquery.autocompleter.css, //www.getlokal.com/css/ui-lightness/jquery-ui-1.8.17.custom.css, //www.getlokal.com/css/facebook/game2bg.css ]

game2bgResultsSuccess:
  javascripts: [-*, //www.getlokal.com/js/jquery.js ]
  stylesheets: [ //www.getlokal.com/css/facebook/game2bg.css ]

game2bgWinnersSuccess:
  javascripts: [-*, //www.getlokal.com/js/jquery.js ]
  stylesheets: [ //www.getlokal.com/css/facebook/game2bg.css ]

game2bgSplashSuccess:
  stylesheets: [ //www.getlokal.com/css/facebook/game2bg.css ]





# Big racing (Ro)
game2roSuccess:
  javascripts: [-*, /js/jquery.js, /js/jquery-ui.js, /js/jquery.tinyscrollbar.min.js ]
  stylesheets: [ /css/jquery.rating.css, /sfFormExtraPlugin/css/jquery.autocompleter.css, /css/ui-lightness/jquery-ui-1.8.17.custom.css, /css/facebook/game2ro.css ]

game2roResultsSuccess:
  javascripts: [-*, /js/jquery.js, /fancybox/jquery.fancybox-1.3.4.pack.js ]
  stylesheets: [ /css/facebook/game2ro.css ]

game2roWinnersSuccess:
  javascripts: [-*, /js/jquery.js ]
  stylesheets: [ /css/facebook/game2ro.css ]

game2roSplashSuccess:
  stylesheets: [ /css/facebook/game2ro.css ]





# Macedonian game
game2mkSuccess:
  javascripts: [-*, //www.getlokal.com/js/jquery.js, //www.getlokal.com/js/jquery-ui.js, //www.getlokal.com/js/jquery.tinyscrollbar.min.js ]
  stylesheets: [ //www.getlokal.com/css/jquery.rating.css, //www.getlokal.com/sfFormExtraPlugin/css/jquery.autocompleter.css, //www.getlokal.com/css/ui-lightness/jquery-ui-1.8.17.custom.css, //www.getlokal.com/css/facebook/game2mk.css ]

game2mkResultsSuccess:
  javascripts: [-*, //www.getlokal.com/js/jquery.js ]
  stylesheets: [ //www.getlokal.com/css/facebook/game2mk.css ]

game2mkWinnersSuccess:
  javascripts: [-*, //www.getlokal.com/js/jquery.js ]
  stylesheets: [ //www.getlokal.com/css/facebook/game2mk.css ]

game2mkSplashSuccess:
  stylesheets: [ //www.getlokal.com/css/facebook/game2mk.css ]



# Lucky three (BG, MK, SR) 
game3Success:
  javascripts: [-*, /js/jquery.js, /js/jquery-ui.js, /js/jquery.tinyscrollbar.min.js ]
  stylesheets: [ /sfFormExtraPlugin/css/jquery.autocompleter.css, /css/ui-lightness/jquery-ui-1.8.17.custom.css, /css/facebook/game3.css ]

game3ResultsSuccess:
  javascripts: [-*, /js/jquery.js ]
  stylesheets: [ /css/facebook/game3.css ]

game3WinnersSuccess:
  javascripts: [-*, /js/jquery.js ]
  stylesheets: [ /css/facebook/game3.css ]

game3SplashSuccess:
  stylesheets: [ /css/facebook/game3.css ]

# FOR DEVLOKAL
#game3Success:
#  javascripts: [-*, jquery.js, jquery-ui.js, jquery.tinyscrollbar.min.js ]
#  stylesheets: [ /sfFormExtraPlugin/css/jquery.autocompleter.css, /css/ui-lightness/jquery-ui-1.8.17.custom.css, /css/facebook/game3.css ]
#
#game3ResultsSuccess:
#  javascripts: [-*, /js/jquery.js ]
#  stylesheets: [ /css/facebook/game3.css ]
#
#game3WinnersSuccess:
#  javascripts: [-*, /js/jquery.js ]
#  stylesheets: [ /css/facebook/game3.css ]
#
#game3SplashSuccess:
#  stylesheets: [ /css/facebook/game3.css ]

  
  
# COPY GAME
game2cbgSuccess:
  javascripts: [-*, //www.getlokal.com/js/jquery.js, //www.getlokal.com/js/jquery-ui.js, //www.getlokal.com/js/jquery.tinyscrollbar.min.js ]
  stylesheets: [ //www.getlokal.com/css/jquery.rating.css, //www.getlokal.com/sfFormExtraPlugin/css/jquery.autocompleter.css, //www.getlokal.com/css/ui-lightness/jquery-ui-1.8.17.custom.css, //www.getlokal.com/css/facebook/game2ro.css ]

game2cbgResultsSuccess:
  javascripts: [-*, //www.getlokal.com/js/jquery.js ]
  stylesheets: [ //www.getlokal.com/css/facebook/game2ro.css ]

game2cbgWinnersSuccess:
  javascripts: [-*, //www.getlokal.com/js/jquery.js ]
  stylesheets: [ //www.getlokal.com/css/facebook/game2ro.css ]

game2cbgSplashSuccess:
  stylesheets: [ //www.getlokal.com/css/facebook/game2ro.css ]
  
  
#game4TheWall
game4Success:
  javascripts: [-*, /js/jquery.js, /js/jquery-ui.js, /js/jquery.tinyscrollbar.min.js ]
  stylesheets: [ /css/jquery.rating.css, /sfFormExtraPlugin/css/jquery.autocompleter.css,  /css/ui-lightness/jquery-ui-1.8.17.custom.css, /css/facebook/game4.css ]

reviewManiaSuccess:
  stylesheets: [ /css/facebook/gameReviewmk.css ]