generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Category
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          category_event_category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        hide: [created_at, updated_at, root]
      list:    
        display: [ title, is_active ]
        object_actions:
          classification: { action: classification }
          _edit: ~
          _delete: ~
      filter: 
        class: false
      form:    ~
      edit:    ~
      new:     ~
