default:
  is_secure: true
  credentials: [[category_article_bg, category_article_ro, category_article_sr, category_article_mk, category_article_fi, category_article_me, category_article_ru]]
logout:
    is_secure: false