generator:
  class: sfDoctrineGenerator
  param:
    model_class:           UserProfile
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user_profile_writereviewgame
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display:      [first_name,email_address,_vouchers]
        table_method:  getQueryForAdmin
        actions: { } 
        object_actions:   { }   
        batch_actions:   { } 
      filter:  
        display:  [is_active, id, first_name, last_name, email_address, city_id, birthdate, gender, created_at, updated_at, week_id, status, review_created_at] 
        class: backendAddReviewGameFilter
      form:    ~      
      edit:    ~
      new:     ~
