<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/12/02 11:02:24
$this->security = array (
  'vouchers' => 
  array (
    'is_secure' => true,
  ),
  'deletereview' => 
  array (
    'is_secure' => true,
  ),
  'messages' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
