<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/12/02 10:09:48
$this->security = array (
  '_feed' => 
  array (
    'is_secure' => true,
  ),
  'keepalive' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
