<?php
// auto-generated by sfCacheConfigHandler
// date: 2014/12/02 09:53:45
$this->addCache($moduleName, '_headerLocations', array('withLayout' => false, 'lifeTime' => 86400, 'clientLifeTime' => 86400, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, '_column', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => true, 'vary' => array ()));
$this->addCache($moduleName, '_boxCategories', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => true, 'vary' => array ()));
$this->addCache($moduleName, '_boxCategoriesMenu', array('withLayout' => false, 'lifeTime' => 7200, 'clientLifeTime' => 7200, 'contextual' => true, 'vary' => array ()));
$this->addCache($moduleName, '_boxSlider2', array('withLayout' => false, 'lifeTime' => 7200, 'clientLifeTime' => 7200, 'contextual' => true, 'vary' => array ()));
$this->addCache($moduleName, '_boxReviews', array('withLayout' => false, 'lifeTime' => 7200, 'clientLifeTime' => 7200, 'contextual' => true, 'vary' => array ()));
$this->addCache($moduleName, '_boxReview', array('withLayout' => false, 'lifeTime' => 7200, 'clientLifeTime' => 7200, 'contextual' => true, 'vary' => array ()));
$this->addCache($moduleName, '_boxVip', array('withLayout' => false, 'lifeTime' => 7200, 'clientLifeTime' => 7200, 'contextual' => true, 'vary' => array ()));
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

