<?php
// auto-generated by sfViewConfigHandler
// date: 2014/12/02 09:53:44
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'addCompanySuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'showSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'reservatioSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'pppSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'geocodusSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'addCompanySuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('font-awesome.min.css', '', array ());
  $response->addStylesheet('bootstrap.css', '', array ());
  $response->addStylesheet('style.css', '', array ());
  $response->addStylesheet('settings.css', '', array ());
  $response->addStylesheet('style1.css', '', array ());
  $response->addStylesheet('/images/favicon.ico', '', array ());
  $response->addStylesheet('prettyPhoto', '', array ());
  $response->addStylesheet('component', '', array ());
  $response->addJavascript('infobox.js', '', array ());
}
else if ($templateName.$this->viewName == 'showSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('font-awesome.min.css', '', array ());
  $response->addStylesheet('bootstrap.css', '', array ());
  $response->addStylesheet('style.css', '', array ());
  $response->addStylesheet('settings.css', '', array ());
  $response->addStylesheet('style1.css', '', array ());
  $response->addStylesheet('/images/favicon.ico', '', array ());
  $response->addStylesheet('prettyPhoto', '', array ());
  $response->addStylesheet('component', '', array ());
  $response->addStylesheet('ui-lightness/jquery-ui-1.8.16.custom.css', '', array ());
}
else if ($templateName.$this->viewName == 'reservatioSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('font-awesome.min.css', '', array ());
  $response->addStylesheet('bootstrap.css', '', array ());
  $response->addStylesheet('style.css', '', array ());
  $response->addStylesheet('settings.css', '', array ());
  $response->addStylesheet('style1.css', '', array ());
  $response->addStylesheet('/images/favicon.ico', '', array ());
  $response->addStylesheet('prettyPhoto', '', array ());
  $response->addStylesheet('component', '', array ());
  $response->addStylesheet('ui-lightness/jquery-ui-1.8.16.custom.css', '', array ());
}
else if ($templateName.$this->viewName == 'pppSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('font-awesome.min.css', '', array ());
  $response->addStylesheet('bootstrap.css', '', array ());
  $response->addStylesheet('style.css', '', array ());
  $response->addStylesheet('settings.css', '', array ());
  $response->addStylesheet('style1.css', '', array ());
  $response->addStylesheet('/images/favicon.ico', '', array ());
  $response->addStylesheet('prettyPhoto', '', array ());
  $response->addStylesheet('component', '', array ());
  $response->addStylesheet('ui-lightness/jquery-ui-1.8.16.custom.css', '', array ());
}
else if ($templateName.$this->viewName == 'geocodusSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addJavascript('jquery-1.10.2.min.js', '', array ());
  $response->addJavascript('geocodus.js', '', array ());
  $response->addJavascript('http://maps.google.com/maps/api/js?sensor=true', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('font-awesome.min.css', '', array ());
  $response->addStylesheet('bootstrap.css', '', array ());
  $response->addStylesheet('style.css', '', array ());
  $response->addStylesheet('settings.css', '', array ());
  $response->addStylesheet('style1.css', '', array ());
  $response->addStylesheet('/images/favicon.ico', '', array ());
  $response->addStylesheet('prettyPhoto', '', array ());
  $response->addStylesheet('component', '', array ());
}

