addCompanySuccess:
  javascripts: [infobox.js]

showSuccess:
  stylesheets: [ui-lightness/jquery-ui-1.8.16.custom.css]

reservatioSuccess:
    stylesheets: [ui-lightness/jquery-ui-1.8.16.custom.css]

pppSuccess:
    stylesheets: [ui-lightness/jquery-ui-1.8.16.custom.css]

geocodusSuccess:
    stylesheets: [-*]
    javascripts: [-*, jquery-1.10.2.min.js, geocodus.js, "http://maps.google.com/maps/api/js?sensor=true"]