generator:
  class: sfDoctrineGenerator
  param:
    model_class:           getWeekend
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          get_weekend
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:       [ _thumb, title, body, aired_on ]
        table_method:  getQueryForAdmin
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
