generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Slider
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          slider
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:        [ _thumb, title, rank, is_active, body, link, created_at ]
        table_method:  getQueryForAdmin
      filter:
        display: [title, title_en, title_ru, body, body_en, body_ru, link, link_en, link_ru, rank, whole_country, is_active, created_at, updated_at, filename, sectors_list, cities_list]
      form:    ~
      edit:    ~
      new:     ~
